all_files <- c(
  # "R/aaa-auto.R",
  "R/adjacency.R",
  "R/assortativity.R",
  "R/attributes.R",
  "R/basic.R",
  "R/bipartite.R",
  "R/centrality.R",
  "R/centralization.R",
  "R/cliques.R",
  "R/cocitation.R",
  "R/cohesive.blocks.R",
  "R/coloring.R",
  "R/community.R",
  "R/components.R",
  "R/console.R",
  "R/conversion.R",
  "R/data_frame.R",
  "R/decomposition.R",
  "R/degseq.R",
  "R/demo.R",
  "R/efficiency.R",
  "R/embedding.R",
  "R/env-and-data.R",
  "R/epi.R",
  "R/eulerian.R",
  "R/fit.R",
  "R/flow.R",
  "R/foreign.R",
  "R/games.R",
  "R/glet.R",
  "R/has.R",
  "R/hrg.R",
  "R/idx.R",
  "R/igraph-package.R",
  "R/incidence.R",
  "R/indexing.R",
  "R/interface.R",
  "R/iterators.R",
  "R/layout.R",
  "R/layout_drl.R",
  "R/lazyeval.R",
  "R/make.R",
  "R/minimum.spanning.tree.R",
  "R/motifs.R",
  "R/nexus.R",
  "R/operators.R",
  "R/other.R",
  "R/package.R",
  "R/palette.R",
  "R/par.R",
  "R/paths.R",
  "R/plot.R",
  "R/plot.common.R",
  "R/plot.shapes.R",
  "R/pp.R",
  "R/print.R",
  "R/printr.R",
  "R/random_walk.R",
  "R/rewire.R",
  "R/scan.R",
  "R/scg.R",
  "R/sgm.R",
  "R/similarity.R",
  "R/simple.R",
  "R/sir.R",
  "R/socnet.R",
  "R/sparsedf.R",
  "R/structural.properties.R",
  "R/structure.info.R",
  "R/test.R",
  "R/tkplot.R",
  "R/topology.R",
  "R/trees.R",
  "R/triangles.R",
  "R/utils.R",
  "R/uuid.R",
  "R/versions.R",
  "R/weakref.R",
  "R/zzz-deprecate.R",
  "demo/centrality.R",
  "demo/cohesive.R",
  "demo/community.R",
  "demo/crashR.R",
  "demo/hrg.R",
  "demo/smallworld.R",
  "tests/testthat.R",
  "tests/testthat/_snaps/plot/basic-graph.svg",
  "tests/testthat/_snaps/print.md",
  "tests/testthat/_snaps/vs-es-printing.md",
  "tests/testthat/_snaps/vs-es.md",
  "tests/testthat/celegansneural.gml.gz",
  "tests/testthat/dyad.census.R",
  "tests/testthat/football.gml.gz",
  "tests/testthat/helper.R",
  "tests/testthat/power.gml.gz",
  "tests/testthat/test-constructor-modifiers.R",
  "tests/testthat/test-graph-ids.R",
  "tests/testthat/test-index-es.R",
  "tests/testthat/test-isomorphism.R",
  "tests/testthat/test-iterators.R",
  "tests/testthat/test-make.R",
  "tests/testthat/test-make_graph.R",
  "tests/testthat/test-make_lattice.R",
  "tests/testthat/test-new-layout-api.R",
  "tests/testthat/test-notable.R",
  "tests/testthat/test-old-data-type.R",
  "tests/testthat/test-plot.R",
  "tests/testthat/test-random_walk.R",
  "tests/testthat/test-version.R",
  "tests/testthat/test-versions.R",
  "tests/testthat/test-vs-es-printing.R",
  "tests/testthat/test-vs-es-quirks.R",
  "tests/testthat/test-vs-es.R",
  "tests/testthat/test-vs-operators.R",
  "tests/testthat/test-weakref.R",
  "tests/testthat/test_add.edges.R",
  "tests/testthat/test_add.vertices.R",
  "tests/testthat/test_adjacency.spectral.embedding.R",
  "tests/testthat/test_all.st.cuts.R",
  "tests/testthat/test_alpha.centrality.R",
  "tests/testthat/test_are.connected.R",
  "tests/testthat/test_arpack.R",
  "tests/testthat/test_articulation.points.R",
  "tests/testthat/test_as.directed.R",
  "tests/testthat/test_as.undirected.R",
  "tests/testthat/test_assortativity.R",
  "tests/testthat/test_attributes.R",
  "tests/testthat/test_authority.score.R",
  "tests/testthat/test_average.path.length.R",
  "tests/testthat/test_ba.game.R",
  "tests/testthat/test_betweenness.R",
  "tests/testthat/test_biconnected.components.R",
  "tests/testthat/test_bipartite.projection.R",
  "tests/testthat/test_bipartite.random.game.R",
  "tests/testthat/test_bonpow.R",
  "tests/testthat/test_bridges.R",
  "tests/testthat/test_bug-1019624.R",
  "tests/testthat/test_bug-1032819.R",
  "tests/testthat/test_bug-1033045.R",
  "tests/testthat/test_bug-1073705-indexing.R",
  "tests/testthat/test_bug-1073800-clique.R",
  "tests/testthat/test_bug-154.R",
  "tests/testthat/test_canonical.permutation.R",
  "tests/testthat/test_cliques.R",
  "tests/testthat/test_closeness.R",
  "tests/testthat/test_clusters.R",
  "tests/testthat/test_coloring.R",
  "tests/testthat/test_communities.R",
  "tests/testthat/test_constraint.R",
  "tests/testthat/test_contract.vertices.R",
  "tests/testthat/test_correlated.R",
  "tests/testthat/test_count.multiple.R",
  "tests/testthat/test_decompose.graph.R",
  "tests/testthat/test_degree.R",
  "tests/testthat/test_degseq.R",
  "tests/testthat/test_delete.edges.R",
  "tests/testthat/test_delete.vertices.R",
  "tests/testthat/test_deprecated_indexing_functions.R",
  "tests/testthat/test_diameter.R",
  "tests/testthat/test_dimSelect.R",
  "tests/testthat/test_dominator.tree.R",
  "tests/testthat/test_dot.product.game.R",
  "tests/testthat/test_dyad.census.R",
  "tests/testthat/test_edge.betweenness.R",
  "tests/testthat/test_edge.betweenness.community.R",
  "tests/testthat/test_edge.connectivity.R",
  "tests/testthat/test_edgenames.R",
  "tests/testthat/test_efficiency.R",
  "tests/testthat/test_eulerian.R",
  "tests/testthat/test_evcent.R",
  "tests/testthat/test_farthest_vertices.R",
  "tests/testthat/test_fastgreedy.community.R",
  "tests/testthat/test_forestfire.R",
  "tests/testthat/test_get.adjacency.R",
  "tests/testthat/test_get.adjlist.R",
  "tests/testthat/test_get.all.shortest.paths.R",
  "tests/testthat/test_get.diameter.R",
  "tests/testthat/test_get.edge.R",
  "tests/testthat/test_get.edgelist.R",
  "tests/testthat/test_get.incidence.R",
  "tests/testthat/test_get.shortest.paths.R",
  "tests/testthat/test_girth.R",
  "tests/testthat/test_graph.adhesion.R",
  "tests/testthat/test_graph.adjacency.R",
  "tests/testthat/test_graph.adjlist.R",
  "tests/testthat/test_graph.atlas.R",
  "tests/testthat/test_graph.bfs.R",
  "tests/testthat/test_graph.bipartite.R",
  "tests/testthat/test_graph.complementer.R",
  "tests/testthat/test_graph.compose.R",
  "tests/testthat/test_graph.coreness.R",
  "tests/testthat/test_graph.data.frame.R",
  "tests/testthat/test_graph.de.bruijn.R",
  "tests/testthat/test_graph.density.R",
  "tests/testthat/test_graph.dfs.R",
  "tests/testthat/test_graph.edgelist.R",
  "tests/testthat/test_graph.eigen.R",
  "tests/testthat/test_graph.formula.R",
  "tests/testthat/test_graph.isoclass.R",
  "tests/testthat/test_graph.kautz.R",
  "tests/testthat/test_graph.knn.R",
  "tests/testthat/test_graph.maxflow.R",
  "tests/testthat/test_graph.mincut.R",
  "tests/testthat/test_graph.subisomorphic.lad.R",
  "tests/testthat/test_graph.subisomorphic.vf2.R",
  "tests/testthat/test_graphNEL.R",
  "tests/testthat/test_graphlets.R",
  "tests/testthat/test_hrg.R",
  "tests/testthat/test_hsbm.R",
  "tests/testthat/test_identical_graphs.R",
  "tests/testthat/test_igraph.options.R",
  "tests/testthat/test_independent.vertex.sets.R",
  "tests/testthat/test_indexing.R",
  "tests/testthat/test_indexing2.R",
  "tests/testthat/test_indexing3.R",
  "tests/testthat/test_is.bipartite.R",
  "tests/testthat/test_is.chordal.R",
  "tests/testthat/test_iterators.R",
  "tests/testthat/test_label.propagation.community.R",
  "tests/testthat/test_laplacian.spectral.embedding.R",
  "tests/testthat/test_largest.cliques.R",
  "tests/testthat/test_largest.independent.vertex.sets.R",
  "tests/testthat/test_layout.fr.R",
  "tests/testthat/test_layout.kk.R",
  "tests/testthat/test_layout.mds.R",
  "tests/testthat/test_layout.merge.R",
  "tests/testthat/test_layout.sugiyama.R",
  "tests/testthat/test_layout_nicely.R",
  "tests/testthat/test_layout_null_singleton.R",
  "tests/testthat/test_leading.eigenvector.community.R",
  "tests/testthat/test_leiden.R",
  "tests/testthat/test_matching.R",
  "tests/testthat/test_maximal_cliques.R",
  "tests/testthat/test_minimal.st.separators.R",
  "tests/testthat/test_minimum.size.separators.R",
  "tests/testthat/test_modularity_matrix.R",
  "tests/testthat/test_motifs.R",
  "tests/testthat/test_multilevel.community.R",
  "tests/testthat/test_neighborhood.R",
  "tests/testthat/test_neighbors.R",
  "tests/testthat/test_operators.R",
  "tests/testthat/test_operators3.R",
  "tests/testthat/test_operators4.R",
  "tests/testthat/test_optimal.community.R",
  "tests/testthat/test_pajek.R",
  "tests/testthat/test_print.R",
  "tests/testthat/test_psumtree.R",
  "tests/testthat/test_read_graph.R",
  "tests/testthat/test_rewire.R",
  "tests/testthat/test_sample.R",
  "tests/testthat/test_sbm.game.R",
  "tests/testthat/test_scan.R",
  "tests/testthat/test_sdf.R",
  "tests/testthat/test_sgm.R",
  "tests/testthat/test_sir.R",
  "tests/testthat/test_sphere.R",
  "tests/testthat/test_topology.R",
  "tests/testthat/test_transitivity.R",
  "tests/testthat/test_trees.R",
  "tests/testthat/test_triangles.R",
  "tests/testthat/test_unfold.tree.R",
  "tests/testthat/test_walktrap.community.R",
  "tests/testthat/test_watts.strogatz.game.R",
  "tests/testthat/test_weighted_cliques.R",
  NULL
)




# egrep -lR "graph_from_literal|make_graph[(] *~|edges[(] *c[(]" demo tests R | sort | pbcopy
exclude_literal <- c(
  # "R/adjacency.R",
  # "R/attributes.R",
  # "R/cohesive.blocks.R",
  # "R/data_frame.R",
  # "R/decomposition.R",
  # "R/eulerian.R",
  # "R/flow.R",
  # "R/igraph-package.R",
  # "R/interface.R",
  # "R/iterators.R",
  # "R/layout.R",
  # "R/make.R",
  # "R/operators.R",
  # "R/paths.R",
  # "R/structural.properties.R",
  # "R/topology.R",
  # "R/zzz-deprecate.R",
  # "demo/centrality.R",
  # "demo/community.R",
  # "demo/crashR.R",
  # "demo/smallworld.R",
  # "tests/testthat/test-constructor-modifiers.R",
  # "tests/testthat/test-make.R",
  # "tests/testthat/test-make_lattice.R",
  # "tests/testthat/test-vs-es-printing.R",
  # "tests/testthat/test_add.vertices.R",
  # "tests/testthat/test_all.st.cuts.R",
  # "tests/testthat/test_are.connected.R",
  # "tests/testthat/test_as.directed.R",
  # "tests/testthat/test_as.undirected.R",
  # "tests/testthat/test_attributes.R",
  # "tests/testthat/test_betweenness.R",
  # "tests/testthat/test_bipartite.projection.R",
  # "tests/testthat/test_bonpow.R",
  # "tests/testthat/test_bug-1033045.R",
  # "tests/testthat/test_closeness.R",
  # "tests/testthat/test_coloring.R",
  # "tests/testthat/test_delete.edges.R",
  # "tests/testthat/test_delete.vertices.R",
  # "tests/testthat/test_dominator.tree.R",
  # "tests/testthat/test_dot.product.game.R",
  # "tests/testthat/test_edge.betweenness.R",
  # "tests/testthat/test_edge.connectivity.R",
  # "tests/testthat/test_efficiency.R",
  # "tests/testthat/test_eulerian.R",
  # "tests/testthat/test_evcent.R",
  # "tests/testthat/test_farthest_vertices.R",
  # "tests/testthat/test_graph.adhesion.R",
  # "tests/testthat/test_graph.formula.R",
  # "tests/testthat/test_graph.subisomorphic.lad.R",
  # "tests/testthat/test_indexing3.R",
  # "tests/testthat/test_is.chordal.R",
  # "tests/testthat/test_iterators.R",
  # "tests/testthat/test_layout.sugiyama.R",
  # "tests/testthat/test_minimum.size.separators.R",
  # "tests/testthat/test_operators.R",
  # "tests/testthat/test_operators3.R",
  # "tests/testthat/test_operators4.R",
  # "tests/testthat/test_triangles.R",
  # "tests/testthat/test_weighted_cliques.R",
  NULL
)

normalize_igraph_arrows <- function(pd) {
  if (length(pd$token) == 0) {
    return(pd)
  }

  if (pd$token[[1]] %in% c("'-'", "'+'")) {
    if (pd$token_before[[1]] %in% c("'-'", "'+'")) {
      if (!(pd$token_after[[1]] %in% c("'-'", "'+'"))) {
        pd$spaces[[1]] <- 1L
      }
    }
  }

  if (nrow(pd) > 1) {
    evens <- seq.int(2L, nrow(pd), by = 2L)
    if (all(pd$token[evens] %in% c("'-'", "'+'"))) {
      after_ops <- pd$token_after[evens] %in% c("'-'", "'+'")
      pd$spaces[evens][after_ops] <- 0L
    }
  }
  pd
}

igraph_style <- function(scope = "tokens", ...) {
  style <- styler::tidyverse_style(scope = scope, ...)

  if ("space" %in% names(style)) {
    style$space <- c(
      style$space,
      list(
        normalize_igraph_arrows = normalize_igraph_arrows
      )
    )

    style$style_guide_name <- "igraph_style"
    style$style_guide_version <- "0.0.4"
  }

  style
}

styler::style_pkg(
  # exclude_files = setdiff(all_files, exclude_literal),
  exclude_files = "aaa-auto.R",
  style = igraph_style,
  # strict = FALSE,
  # scope = "spaces"
  # scope = "indention"
  # scope = "line_breaks"
  scope = "tokens"
)
