name: Bug report form
description: Report a defect in the R interface of igraph
body:
  - type: markdown
    attributes:
      value: >
        _Note:_ This form is for reporting bugs only. If you are seeking support, or looking for help with installation, please use [the forum](https://igraph.discourse.group/).

  - type: textarea
    attributes:
      label: What happens, and what did you expect instead?
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To reproduce
      description: >
        Please show a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can understand what the issue is and re-create it on our end.

        For R code, please use the [reprex package](https://reprex.tidyverse.org/):

        1. copy your code to the clipboard

        2. run `reprex::reprex()`

        3. paste the results in the text box below
    validations:
      required: true

  - type: textarea
    attributes:
      label: System information
      description: >
        Enter all relevant information about your system (operating system, R version, where you obtained R from, etc.), including the output of `sessionInfo()`.
    validations:
      required: false
