me <- unname(desc::desc_get("Package"))
strong <- unlist(tools::package_dependencies(me, which = "most", reverse = TRUE), use.names = FALSE)
# second <- unlist(tools::package_dependencies(strong, reverse = TRUE, recursive = TRUE), use.names = FALSE)
second <- unlist(tools::package_dependencies(strong, reverse = TRUE), use.names = FALSE)
bad <- c("streamDAG", "Seurat", "bsts")
packages <- setdiff(unique(c(strong, second)), bad)

revdepcheck::cloud_check(revdep_packages = packages)
revdepcheck::cloud_status()
revdepcheck::cloud_report()
