name: "Action to auto-style a package"

runs:
  using: "composite"
  steps:
    - name: Check air.toml
      id: check
      run: |
        set -x
        if [ -f air.toml ]; then
          echo enabled=true >> $GITHUB_OUTPUT
        else
          echo enabled=false >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Install air
      if: ${{ steps.check.outputs.scope }}
      uses: posit-dev/setup-air@v1

    - name: Run air
      if: ${{ steps.check.outputs.scope }}
      run: |
        air format .
      shell: Rscript {0}
