name: 'Custom steps to run after R packages are installed'

runs:
  using: "composite"
  steps:
    - uses: ankane/setup-postgres@v1
      if: env.DM_TEST_SRC == 'test-postgres'

    - name: Create database
      if: env.DM_TEST_SRC == 'test-postgres'
      run: |
        createdb ${USER}
      shell: bash

    # Must happen after installing system dependencies,
    # https://github.com/ankane/setup-mariadb/issues/2
    - uses: ankane/setup-mariadb@v1
      if: env.DM_TEST_SRC == 'test-maria'
      with:
        mariadb-version: 10.11

    - uses: ankane/setup-mysql@v1
      if: env.DM_TEST_SRC == 'test-mysql-maria'
      with:
        mysql-version: "8.0"

    - name: Create database (MariaDB), set it to UTF-8, add time zone info
      if: env.DM_TEST_SRC == 'test-maria' || env.DM_TEST_SRC == 'test-mysql-maria'
      run: |
        mysql -e "CREATE DATABASE IF NOT EXISTS test; ALTER DATABASE test CHARACTER SET 'utf8'; FLUSH PRIVILEGES;"
      shell: bash

    - uses: ankane/setup-sqlserver@v1
      if: env.DM_TEST_SRC == 'test-mssql'
      with:
        accept-eula: true

    - name: Create database (SQL Server)
      if: env.DM_TEST_SRC == 'test-mssql'
      run: |
        sqlcmd -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE test;'
      shell: bash

    - name: Set ODBCSYSINI (SQL Server)
      if: env.DM_TEST_SRC == 'test-mssql'
      run: |
        ln -s /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.*.so.* /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.so
        echo "ODBCSYSINI=${{ github.workspace }}/.github/odbc" | tee -a $GITHUB_ENV
      shell: bash

    - name: Allow slower examples
      run: |
        # FIXME: Slow examples in dm?
        echo "_R_CHECK_EXAMPLE_TIMING_THRESHOLD_=15" | tee -a $GITHUB_ENV
      shell: bash
