#!/bin/bash
#
# Fixes the lexers generated by bison/flex so they don't have exit()
# statements (which we won't hit anyway)

for fname in src/*-lexer.c; do
    # Remove unused exit points from the lexer
    cat ${fname} | grep -v '^\s*exit.*YY_EXIT_FAILURE' >${fname}.new
    mv ${fname}.new ${fname}

    # Remove 'noreturn' declaration from exit points
    cat ${fname} | sed -e 's/void yynoreturn/void/g' >${fname}.new
    mv ${fname}.new ${fname}

    # flex on Ubuntu 20.04 generates 'int yyget_leng'; flex on macOS generates
    # 'yy_size_t yyget_leng'. We need to be consistent as we also declare
    # yyget_leng ourselves in the parser and we use yy_size_t there
    cat ${fname} | sed -e 's/int yyget_leng/yy_size_t yyget_leng/g' >${fname}.new
    mv ${fname}.new ${fname}
done

