#!/usr/bin/env Rscript
#
# Generator for per-function argument-migration helpers.
#
# Reads the declarative registry in tools/migrations.R and, for each entry,
# emits one self-contained internal helper `handle_args_<fn>()` at
# R/handle-args-<fn>.R. The generated helpers recover legacy positional calls
# made against a function's pre-migration signature after `...` was inserted.
#
# Usage:
#   Rscript tools/generate-migrations.R
#
# The output is deterministic (entries sorted alphabetically by `fn`) and
# idempotent (running twice produces no diff). A CI check regenerates and fails
# on drift; see .github/workflows/check-migrations.yaml.
#
# Base R only -- no package needs to be loaded to run this.

# ---- locate paths relative to this script --------------------------------

migration_paths <- function() {
  # When run via `Rscript tools/generate-migrations.R`, the working directory is
  # the package root.
  root <- getwd()
  list(
    registry = file.path(root, "tools", "migrations.R"),
    out_dir = file.path(root, "R")
  )
}

# ---- registry loading + validation ----------------------------------------

load_migrations <- function(registry_path) {
  env <- new.env(parent = baseenv())
  sys.source(registry_path, envir = env, keep.source = FALSE)
  if (!exists("migrations", envir = env, inherits = FALSE)) {
    stop(
      "`",
      registry_path,
      "` must define a `migrations` list.",
      call. = FALSE
    )
  }
  migrations <- get("migrations", envir = env)
  lapply(migrations, validate_migration)
}

validate_migration <- function(entry) {
  req <- c("fn", "old", "new")
  missing <- setdiff(req, names(entry))
  if (length(missing)) {
    stop(
      "Migration entry is missing field(s): ",
      paste(missing, collapse = ", "),
      call. = FALSE
    )
  }
  entry$renames <- entry$renames %||% character(0)
  entry$defaults <- entry$defaults %||% list()
  entry$when <- entry$when %||% "3.0.0"

  if (sum(entry$new == "...") != 1L) {
    stop(
      "Migration `",
      entry$fn,
      "`: `new` must contain exactly one \"...\" marker.",
      call. = FALSE
    )
  }

  dots_idx <- which(entry$new == "...")
  entry$head <- entry$new[seq_len(dots_idx - 1L)]
  entry$tail <- if (dots_idx < length(entry$new)) {
    entry$new[(dots_idx + 1L):length(entry$new)]
  } else {
    character(0)
  }
  entry$new_args <- c(entry$head, entry$tail)

  if (length(entry$old) < length(entry$head)) {
    stop(
      "Migration `",
      entry$fn,
      "`: `old` is shorter than the head args of `new`.",
      call. = FALSE
    )
  }
  # Old positional slots beyond the head are the recoverable ones.
  entry$recover_old <- if (length(entry$old) > length(entry$head)) {
    entry$old[(length(entry$head) + 1L):length(entry$old)]
  } else {
    character(0)
  }
  entry$recover_new <- vapply(
    entry$recover_old,
    function(nm) {
      if (nm %in% names(entry$renames)) unname(entry$renames[[nm]]) else nm
    },
    character(1)
  )

  bad <- setdiff(entry$recover_new, entry$tail)
  if (length(bad)) {
    stop(
      "Migration `",
      entry$fn,
      "`: recovered slot(s) ",
      paste(bad, collapse = ", "),
      " do not appear after `...` in `new`.",
      call. = FALSE
    )
  }
  entry
}

`%||%` <- function(x, y) if (is.null(x)) y else x

# ---- rendering -------------------------------------------------------------

# Build the formals list of the generated helper as a single string.
render_formals <- function(entry) {
  head_fmls <- entry$head
  tail_fmls <- vapply(
    entry$tail,
    function(nm) {
      if (nm %in% names(entry$defaults)) {
        paste0(nm, " = ", entry$defaults[[nm]])
      } else {
        nm
      }
    },
    character(1)
  )
  c(head_fmls, "...", tail_fmls, ".user_env = rlang::caller_env()")
}

# Render a character vector literal, e.g. c("a", "b").
render_chr_vec <- function(x) {
  if (length(x) == 0L) {
    return("character(0)")
  }
  paste0("c(", paste0('"', x, '"', collapse = ", "), ")")
}

# Render the `defaults` list literal restricted to recoverable slots, reusing
# the registry's default *expressions* so the runtime identity check compares
# against the true formal default.
render_defaults_list <- function(entry) {
  if (length(entry$recover_new) == 0L) {
    return("list()")
  }
  items <- vapply(
    entry$recover_new,
    function(nm) {
      expr <- if (nm %in% names(entry$defaults)) {
        entry$defaults[[nm]]
      } else {
        "NULL"
      }
      paste0(nm, " = ", expr)
    },
    character(1)
  )
  paste0("list(", paste(items, collapse = ", "), ")")
}

render_migration <- function(entry) {
  fn <- entry$fn
  bindings_items <- paste0(entry$new_args, " = ", entry$new_args)

  header <- c(
    "# Generated by tools/generate-migrations.R from tools/migrations.R — do not edit by hand.",
    "# Regenerate with: Rscript tools/generate-migrations.R",
    "# (Excluded from `air` formatting via air.toml so this layout stays canonical.)",
    "#",
    paste0("# `", fn, "()`'s pre-", entry$when, " signature took its arguments"),
    "# positionally. After `...` was inserted, a legacy positional call lands the",
    "# old arguments in `...`. This helper recovers them, soft-deprecates the",
    "# positional form, and returns the new-API bindings as a named list.",
    "#",
    "# `.user_env` is threaded into `lifecycle::deprecate_soft()` so the warning is",
    "# attributed to the user's call instead of being suppressed as",
    "# package-internal. Public callers must pass `.user_env = rlang::caller_env()`."
  )

  # One formal per line, matching rigraph's hand-written signatures. The file is
  # excluded from `air` (see air.toml) so this layout is canonical.
  fmls <- render_formals(entry)
  fmls_lines <- paste0("  ", fmls)
  fmls_lines[-length(fmls_lines)] <- paste0(
    fmls_lines[-length(fmls_lines)],
    ","
  )
  signature <- c(
    paste0("handle_args_", fn, " <- function("),
    fmls_lines,
    ") {"
  )

  body <- c(
    paste0("  bindings <- list(", paste(bindings_items, collapse = ", "), ")"),
    "",
    "  dots <- list(...)",
    "  if (length(dots) == 0L) {",
    "    return(bindings)",
    "  }",
    "",
    "  # Any *named* dot is an unknown keyword (future extension or a typo); enforce",
    "  # the strict contract. Only a purely positional `...` is treated as a legacy",
    "  # call and recovered below.",
    "  if (any(nzchar(rlang::names2(dots)))) {",
    "    rlang::check_dots_empty(call = .user_env)",
    "  }",
    "",
    paste0("  recover_new <- ", render_chr_vec(entry$recover_new)),
    paste0("  recover_old <- ", render_chr_vec(entry$recover_old)),
    paste0("  defaults <- ", render_defaults_list(entry)),
    "",
    "  if (length(dots) > length(recover_new)) {",
    paste0("    cli::cli_abort(\"Too many arguments passed to {.fn ", fn, "}.\", call = .user_env)"),
    "  }",
    "",
    "  for (i in seq_along(dots)) {",
    "    new_name <- recover_new[[i]]",
    "    # Conflict: the same logical slot was supplied positionally *and* by its",
    "    # new keyword (i.e. the keyword differs from its formal default).",
    "    if (!identical(bindings[[new_name]], defaults[[new_name]])) {",
    "      cli::cli_abort(",
    "        c(",
    "          \"Can't supply {.arg {recover_old[[i]]}} both positionally and as {.arg {new_name}}.\",",
    "          i = \"Drop the positional value and keep {.code {new_name} = }.\"",
    "        ),",
    "        call = .user_env",
    "      )",
    "    }",
    "    bindings[[new_name]] <- dots[[i]]",
    "  }",
    "",
    "  # One consolidated soft-deprecation per call. Key the message on the first",
    "  # renamed slot if there is one, else the first recovered slot.",
    "  rebound <- seq_along(dots)",
    "  renamed <- rebound[recover_old[rebound] != recover_new[rebound]]",
    "  primary <- if (length(renamed)) renamed[[1L]] else 1L",
    "  lifecycle::deprecate_soft(",
    paste0("    when = \"", entry$when, "\","),
    paste0("    what = sprintf(\"", fn, "(%s)\", recover_old[[primary]]),"),
    paste0("    with = if (recover_old[[primary]] != recover_new[[primary]]) sprintf(\"", fn, "(%s)\", recover_new[[primary]]),"),
    "    details = c(",
    paste0("      \"Positional use of the pre-", entry$when, " signature of `", fn, "()` is deprecated.\","),
    "      i = paste0(",
    "        \"Name the argument(s) instead: \",",
    "        toString(sprintf(\"`%s = `\", recover_new[rebound])), \".\"",
    "      )",
    "    ),",
    "    user_env = .user_env",
    "  )",
    "",
    "  bindings",
    "}"
  )

  c(header, "", "#' @noRd", signature, body, "")
}

# ---- driver ----------------------------------------------------------------

generate_migrations <- function(registry_path, out_dir) {
  migrations <- load_migrations(registry_path)

  # Remove stale generated files first so deleted registry entries don't leave
  # orphaned helpers behind.
  stale <- list.files(
    out_dir,
    pattern = "^handle-args-.*\\.R$",
    full.names = TRUE
  )
  if (length(stale)) {
    file.remove(stale)
  }

  fns <- vapply(migrations, function(e) e$fn, character(1))
  migrations <- migrations[order(fns)]

  for (entry in migrations) {
    lines <- render_migration(entry)
    out_path <- file.path(out_dir, paste0("handle-args-", entry$fn, ".R"))
    writeLines(lines, out_path)
    message("wrote ", out_path)
  }
  message("generated ", length(migrations), " migration helper(s)")
  invisible(vapply(migrations, function(e) e$fn, character(1)))
}

# Run when invoked as a script (not when sourced for its functions).
if (sys.nframe() == 0L && !interactive()) {
  paths <- migration_paths()
  generate_migrations(paths$registry, paths$out_dir)
}
