# Dependencies
include $(GLUE_C_SOURCES:.o=.dd)
include $(GLUE_CPP_SOURCES:.o=.dd)

# Include only local dependencies for smaller footprint
# Add trailing backslash and sort
%.dd: %.d
	sed -r 's/([^ ]) ([^ \\])/\1 \\\n  \2/g' $< | sed -r '/^  ([/]|vendor|[.][.])/D;$$s/([^\\])$$/\1 \\/' | { echo "# Generated by deps.mk, do not edit by hand and do not add dependencies to system headers"; read -r header; printf '%s\n' "$$header"; LOCALE=C sort; } > $@
