# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off
# jarl-ignore-file unused_function: irrelevant for _impl functions

# ==== adding-and-deleting-vertices-and-edges ====

add_edge_impl <- function(
  graph,
  from,
  to
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as.numeric(from)
  to <- as.numeric(to)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_add_edge,
    graph,
    from,
    to
  )

  res
}

add_edges_impl <- function(
  graph,
  edges
) {
  # Argument checks
  ensure_igraph(graph)
  edges <- as_igraph_vs(graph, edges)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_add_edges,
    graph,
    edges - 1
  )

  res
}

add_vertices_impl <- function(
  graph,
  nv
) {
  # Argument checks
  ensure_igraph(graph)
  nv <- as.numeric(nv)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_add_vertices,
    graph,
    nv
  )

  res
}

delete_edges_impl <- function(
  graph,
  edges
) {
  # Argument checks
  ensure_igraph(graph)
  edges <- as_igraph_es(graph, edges)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_delete_edges,
    graph,
    edges - 1
  )

  res
}

delete_vertices_idx_impl <- function(
  graph,
  vertices
) {
  # Argument checks
  ensure_igraph(graph)
  vertices <- as_igraph_vs(graph, vertices)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_delete_vertices_idx,
    graph,
    vertices - 1
  )

  res
}

delete_vertices_impl <- function(
  graph,
  vertices
) {
  # Argument checks
  ensure_igraph(graph)
  vertices <- as_igraph_vs(graph, vertices)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_delete_vertices,
    graph,
    vertices - 1
  )

  res
}

# ==== basic-query-operations ====

degree_impl <- function(
  graph,
  vids = V(graph),
  mode = c("all", "out", "in", "total"),
  loops = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  vids <- as_igraph_vs(graph, vids)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  loops <- as.logical(loops)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_degree,
    graph,
    vids - 1,
    mode,
    loops
  )

  res
}

ecount_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_ecount,
    graph
  )

  res
}

edge_impl <- function(
  graph,
  eid
) {
  # Argument checks
  ensure_igraph(graph)
  eid <- as.numeric(eid)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_edge,
    graph,
    eid
  )

  res
}

edges_impl <- function(
  graph,
  eids
) {
  # Argument checks
  ensure_igraph(graph)
  eids <- as_igraph_es(graph, eids)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_edges,
    graph,
    eids - 1
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs(graph, res)
  }
  res
}

get_all_eids_between_impl <- function(
  graph,
  from,
  to,
  directed = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (length(to) != 1) {
    cli::cli_abort(
      "{.arg to} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_all_eids_between,
    graph,
    from - 1,
    to - 1,
    directed
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_es(graph, res)
  }
  res
}

get_eid_impl <- function(
  graph,
  from,
  to,
  directed = TRUE,
  error = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (length(to) != 1) {
    cli::cli_abort(
      "{.arg to} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  directed <- as.logical(directed)
  error <- as.logical(error)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_eid,
    graph,
    from - 1,
    to - 1,
    directed,
    error
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_es(graph, res)
  }
  res
}

get_eids_impl <- function(
  graph,
  pairs,
  directed = TRUE,
  error = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  pairs <- as_igraph_vs(graph, pairs)
  directed <- as.logical(directed)
  error <- as.logical(error)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_eids,
    graph,
    pairs - 1,
    directed,
    error
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_es(graph, res)
  }
  res
}

incident_impl <- function(
  graph,
  vid,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  vid <- as_igraph_vs(graph, vid)
  if (length(vid) != 1) {
    cli::cli_abort(
      "{.arg vid} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_incident,
    graph,
    vid - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_es(graph, res)
  }
  res
}

is_directed_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_directed,
    graph
  )

  res
}

neighbors_impl <- function(
  graph,
  vid,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  vid <- as_igraph_vs(graph, vid)
  if (length(vid) != 1) {
    cli::cli_abort(
      "{.arg vid} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_neighbors,
    graph,
    vid - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs(graph, res)
  }
  res
}

vcount_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_vcount,
    graph
  )

  res
}

# ==== graph-constructors-and-destructors ====

copy_impl <- function(
  from
) {
  # Argument checks
  ensure_igraph(from)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_copy,
    from
  )

  res
}

empty_attrs_impl <- function(
  n,
  directed
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_empty_attrs,
    n,
    directed
  )

  res
}

empty_impl <- function(
  n = 0,
  directed = TRUE
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_empty,
    n,
    directed
  )

  res
}

# ==== misc-helper-functions ====

expand_path_to_pairs_impl <- function(
  path
) {
  # Argument checks
  path <- as_igraph_vs(path, path)
  path <- path - 1

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_expand_path_to_pairs,
    path
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs(path, res)
  }
  res
}

invalidate_cache_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_invalidate_cache,
    graph
  )

  res
}

is_same_graph_impl <- function(
  graph1,
  graph2
) {
  # Argument checks
  ensure_igraph(graph1)
  ensure_igraph(graph2)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_same_graph,
    graph1,
    graph2
  )

  res
}
