# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off
# jarl-ignore-file unused_function: irrelevant for _impl functions

# ==== distances-and-metrics ====

average_path_length_dijkstra_impl <- function(
  graph,
  weights = NULL,
  directed = TRUE,
  unconnected = TRUE,
  details = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  directed <- as.logical(directed)
  unconnected <- as.logical(unconnected)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_average_path_length_dijkstra,
    graph,
    weights,
    directed,
    unconnected
  )
  if (!details) {
    res <- res$res
  }
  res
}

average_path_length_impl <- function(
  graph,
  directed = TRUE,
  unconn = TRUE,
  details = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  directed <- as.logical(directed)
  unconn <- as.logical(unconn)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_average_path_length,
    graph,
    directed,
    unconn
  )
  if (!details) {
    res <- res$res
  }
  res
}

diameter_dijkstra_impl <- function(
  graph,
  weights = NULL,
  directed = TRUE,
  unconnected = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  directed <- as.logical(directed)
  unconnected <- as.logical(unconnected)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_diameter_dijkstra,
    graph,
    weights,
    directed,
    unconnected
  )

  res
}

diameter_impl <- function(
  graph,
  directed = TRUE,
  unconnected = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  directed <- as.logical(directed)
  unconnected <- as.logical(unconnected)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_diameter,
    graph,
    directed,
    unconnected
  )

  res
}

distances_bellman_ford_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_distances_bellman_ford,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )

  res
}

distances_cutoff_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  mode = c("out", "in", "all", "total"),
  cutoff = -1
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  cutoff <- as.numeric(cutoff)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_distances_cutoff,
    graph,
    from - 1,
    to - 1,
    mode,
    cutoff
  )

  res
}

distances_dijkstra_cutoff_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total"),
  cutoff = -1
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  cutoff <- as.numeric(cutoff)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_distances_dijkstra_cutoff,
    graph,
    from - 1,
    to - 1,
    weights,
    mode,
    cutoff
  )

  res
}

distances_dijkstra_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_distances_dijkstra,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )

  res
}

distances_floyd_warshall_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total"),
  method = c("automatic", "original", "tree")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  method <- switch_igraph_arg(method, "automatic" = 0L, "original" = 1L, "tree" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_distances_floyd_warshall,
    graph,
    from - 1,
    to - 1,
    weights,
    mode,
    method
  )

  res
}

distances_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_distances,
    graph,
    from - 1,
    to - 1,
    mode
  )

  res
}

distances_johnson_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_distances_johnson,
    graph,
    from - 1,
    to - 1,
    weights
  )

  res
}

eccentricity_dijkstra_impl <- function(
  graph,
  vids = V(graph),
  ...,
  weights = NULL,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  check_dots_empty()
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  vids <- as_igraph_vs(graph, vids)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_eccentricity_dijkstra,
    graph,
    weights,
    vids - 1,
    mode
  )
  if (igraph_opt("add.vertex.names") && is_named(graph)) {
    names(res) <- vertex_attr(graph, "name", vids)
  }
  res
}

eccentricity_impl <- function(
  graph,
  vids = V(graph),
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  vids <- as_igraph_vs(graph, vids)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_eccentricity,
    graph,
    vids - 1,
    mode
  )
  if (igraph_opt("add.vertex.names") && is_named(graph)) {
    names(res) <- vertex_attr(graph, "name", vids)
  }
  res
}

girth_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_girth,
    graph
  )
  if (igraph_opt("return.vs.es")) {
    res$circle <- create_vs(graph, res$circle)
  }
  res
}

graph_center_dijkstra_impl <- function(
  graph,
  ...,
  weights = NULL,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  check_dots_empty()
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_graph_center_dijkstra,
    graph,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs(graph, res)
  }
  res
}

graph_center_impl <- function(
  graph,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_graph_center,
    graph,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs(graph, res)
  }
  res
}

path_length_hist_impl <- function(
  graph,
  directed = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_path_length_hist,
    graph,
    directed
  )

  res
}

pseudo_diameter_dijkstra_impl <- function(
  graph,
  weights = NULL,
  start_vid,
  directed = TRUE,
  unconnected = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  start_vid <- as_igraph_vs(graph, start_vid)
  if (length(start_vid) != 1) {
    cli::cli_abort(
      "{.arg start_vid} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  directed <- as.logical(directed)
  unconnected <- as.logical(unconnected)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_pseudo_diameter_dijkstra,
    graph,
    weights,
    start_vid - 1,
    directed,
    unconnected
  )

  res
}

pseudo_diameter_impl <- function(
  graph,
  start_vid,
  directed = TRUE,
  unconnected = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  start_vid <- as_igraph_vs(graph, start_vid)
  if (length(start_vid) != 1) {
    cli::cli_abort(
      "{.arg start_vid} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  directed <- as.logical(directed)
  unconnected <- as.logical(unconnected)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_pseudo_diameter,
    graph,
    start_vid - 1,
    directed,
    unconnected
  )

  res
}

radius_dijkstra_impl <- function(
  graph,
  ...,
  weights = NULL,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  check_dots_empty()
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_radius_dijkstra,
    graph,
    weights,
    mode
  )

  res
}

radius_impl <- function(
  graph,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_radius,
    graph,
    mode
  )

  res
}

voronoi_impl <- function(
  graph,
  generators,
  ...,
  weights = NULL,
  mode = c("out", "in", "all", "total"),
  tiebreaker = c("random", "first", "last")
) {
  # Argument checks
  check_dots_empty()
  ensure_igraph(graph)
  generators <- as_igraph_vs(graph, generators)
  generators <- generators - 1
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  tiebreaker <- switch_igraph_arg(tiebreaker, "first" = 0L, "last" = 1L, "random" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_voronoi,
    graph,
    generators,
    weights,
    mode,
    tiebreaker
  )

  res
}

# ==== shortest-paths ====

get_all_shortest_paths_dijkstra_impl <- function(
  graph,
  from,
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_all_shortest_paths_dijkstra,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vpaths <- lapply(res$vpaths, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$epaths <- lapply(res$epaths, unsafe_create_es, graph = graph, es = E(graph))
  }
  res
}

get_all_shortest_paths_impl <- function(
  graph,
  from,
  to,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_all_shortest_paths,
    graph,
    from - 1,
    to - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vpaths <- lapply(res$vpaths, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$epaths <- lapply(res$epaths, unsafe_create_es, graph = graph, es = E(graph))
  }
  res
}

get_all_simple_paths_impl <- function(
  graph,
  from,
  to = V(graph),
  cutoff = -1,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  cutoff <- as.numeric(cutoff)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_all_simple_paths,
    graph,
    from - 1,
    to - 1,
    cutoff,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs(graph, res)
  }
  res
}

get_k_shortest_paths_impl <- function(
  graph,
  from,
  to,
  ...,
  k,
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  check_dots_empty()
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  k <- as.numeric(k)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (length(to) != 1) {
    cli::cli_abort(
      "{.arg to} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_k_shortest_paths,
    graph,
    weights,
    k,
    from - 1,
    to - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vpaths <- lapply(res$vpaths, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$epaths <- lapply(res$epaths, unsafe_create_es, graph = graph, es = E(graph))
  }
  res
}

get_shortest_path_astar_impl <- function(
  graph,
  from,
  to,
  weights = NULL,
  mode = c("out", "in", "all", "total"),
  heuristic = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (length(to) != 1) {
    cli::cli_abort(
      "{.arg to} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_shortest_path_astar,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- create_vs(graph, res$vertices)
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- create_es(graph, res$edges)
  }
  res
}

get_shortest_path_bellman_ford_impl <- function(
  graph,
  from,
  to,
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (length(to) != 1) {
    cli::cli_abort(
      "{.arg to} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_shortest_path_bellman_ford,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- create_vs(graph, res$vertices)
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- create_es(graph, res$edges)
  }
  res
}

get_shortest_path_dijkstra_impl <- function(
  graph,
  from,
  to,
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (length(to) != 1) {
    cli::cli_abort(
      "{.arg to} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_shortest_path_dijkstra,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- create_vs(graph, res$vertices)
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- create_es(graph, res$edges)
  }
  res
}

get_shortest_path_impl <- function(
  graph,
  from,
  to,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (length(to) != 1) {
    cli::cli_abort(
      "{.arg to} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_shortest_path,
    graph,
    from - 1,
    to - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- create_vs(graph, res$vertices)
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- create_es(graph, res$edges)
  }
  res
}

get_shortest_paths_bellman_ford_impl <- function(
  graph,
  from,
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_shortest_paths_bellman_ford,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- lapply(res$vertices, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- lapply(res$edges, unsafe_create_es, graph = graph, es = E(graph))
  }
  res
}

get_shortest_paths_dijkstra_impl <- function(
  graph,
  from,
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_shortest_paths_dijkstra,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- lapply(res$vertices, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- lapply(res$edges, unsafe_create_es, graph = graph, es = E(graph))
  }
  res
}

get_shortest_paths_impl <- function(
  graph,
  from,
  to = V(graph),
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_shortest_paths,
    graph,
    from - 1,
    to - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- lapply(res$vertices, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- lapply(res$edges, unsafe_create_es, graph = graph, es = E(graph))
  }
  res
}

vertex_path_from_edge_path_impl <- function(
  graph,
  start = NULL,
  edge_path,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  if (!is.null(start)) {
    start <- as_igraph_vs(graph, start)
    if (length(start) != 1) {
      cli::cli_abort(
        "{.arg start} must specify exactly one vertex",
        call = rlang::caller_env()
      )
    }
  }
  edge_path <- as_igraph_es(graph, edge_path)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_vertex_path_from_edge_path,
    graph,
    start - 1,
    edge_path - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs(graph, res)
  }
  res
}

# ==== widest-path-related-functions ====

get_widest_path_impl <- function(
  graph,
  from,
  to,
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (length(to) != 1) {
    cli::cli_abort(
      "{.arg to} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_widest_path,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- create_vs(graph, res$vertices)
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- create_es(graph, res$edges)
  }
  res
}

get_widest_paths_impl <- function(
  graph,
  from,
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  if (length(from) != 1) {
    cli::cli_abort(
      "{.arg from} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_widest_paths,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- lapply(res$vertices, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- lapply(res$edges, unsafe_create_es, graph = graph, es = E(graph))
  }
  res
}

widest_path_widths_dijkstra_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_widest_path_widths_dijkstra,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )

  res
}

widest_path_widths_floyd_warshall_impl <- function(
  graph,
  from = V(graph),
  to = V(graph),
  weights = NULL,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  from <- as_igraph_vs(graph, from)
  to <- as_igraph_vs(graph, to)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_widest_path_widths_floyd_warshall,
    graph,
    from - 1,
    to - 1,
    weights,
    mode
  )

  res
}
