# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== error-codes ====

strerror_impl <- function(
  igraph_errno
) {
  # Argument checks
  igraph_errno <- as.numeric(igraph_errno)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_strerror,
    igraph_errno
  )

  res
}
