# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== spectral-embedding ====

adjacency_spectral_embedding_impl <- function(
  graph,
  no,
  weights = NULL,
  which = c("lm", "la", "sa"),
  scaled = TRUE,
  cvec = strength(graph, weights = weights) / (vcount(graph) - 1),
  options = arpack_defaults()
) {
  # Argument checks
  ensure_igraph(graph)
  no <- as.numeric(no)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  which <- switch_igraph_arg(which, "lm" = 0L, "la" = 2L, "sa" = 3L)
  scaled <- as.logical(scaled)
  cvec <- as.numeric(cvec)
  options <- modify_list(arpack_defaults(), options)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_adjacency_spectral_embedding,
    graph,
    no,
    weights,
    which,
    scaled,
    cvec,
    options
  )

  res
}

dim_select_impl <- function(
  sv
) {
  # Argument checks
  sv <- as.numeric(sv)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_dim_select,
    sv
  )

  res
}

laplacian_spectral_embedding_impl <- function(
  graph,
  no,
  weights = NULL,
  which = c("lm", "la", "sa"),
  type = c("default", "D-A", "DAD", "I-DAD", "OAP"),
  scaled = TRUE,
  options = arpack_defaults()
) {
  # Argument checks
  ensure_igraph(graph)
  no <- as.numeric(no)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  which <- switch_igraph_arg(which, "lm" = 0L, "la" = 2L, "sa" = 3L)
  type <- switch_igraph_arg(type, "default" = if (is_directed(graph)) 3L else 0L,
    "da" = 0L, "d-a" = 0L, "idad" = 1L, "i-dad" = 1L, "dad" = 2L,
    "oap" = 3L)
  scaled <- as.logical(scaled)
  options <- modify_list(arpack_defaults(), options)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_laplacian_spectral_embedding,
    graph,
    no,
    weights,
    which,
    type,
    scaled,
    options
  )

  res
}
