# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off
# jarl-ignore-file unused_function: irrelevant for _impl functions

# ==== cliques ====

clique_number_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_clique_number,
    graph
  )

  res
}

clique_size_hist_impl <- function(
  graph,
  min_size = 0,
  max_size = 0
) {
  # Argument checks
  ensure_igraph(graph)
  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_clique_size_hist,
    graph,
    min_size,
    max_size
  )

  res
}

cliques_callback_closure_impl <- function(
  graph,
  min_size = 0,
  max_size = 0,
  callback
) {
  # Argument checks
  ensure_igraph(graph)
  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)
  if (!is.null(callback)) {
    if (!is.function(callback)) {
      cli::cli_abort("{.arg callback} must be a function")
    }
    callback_wrapped <- function(...) {
      tryCatch(
        {
          out <- callback(...)
          if (is.logical(out) && length(out) == 1 && !is.na(out)) {
            out
          } else {
            rlang::error_cnd(message = "Callback returned a value different from TRUE or FALSE")
          }
        },
        error = function(e) e,
        interrupt = function(e) e
      )
    }
  } else {
    callback_wrapped <- NULL
  }


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_cliques_callback_closure,
    graph,
    min_size,
    max_size,
    callback_wrapped
  )

  res
}

cliques_impl <- function(
  graph,
  min = 0,
  max = 0
) {
  # Argument checks
  ensure_igraph(graph)
  min <- as.numeric(min)
  max <- as.numeric(max)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_cliques,
    graph,
    min,
    max
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs_list(graph, res)
  }
  res
}

is_clique_impl <- function(
  graph,
  candidate,
  directed = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  candidate <- as_igraph_vs(graph, candidate)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_clique,
    graph,
    candidate - 1,
    directed
  )

  res
}

is_complete_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_complete,
    graph
  )

  res
}

largest_cliques_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_largest_cliques,
    graph
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs_list(graph, res)
  }
  res
}

maximal_cliques_callback_closure_impl <- function(
  graph,
  min_size = 0,
  max_size = 0,
  callback
) {
  # Argument checks
  ensure_igraph(graph)
  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)
  if (!is.null(callback)) {
    if (!is.function(callback)) {
      cli::cli_abort("{.arg callback} must be a function")
    }
    callback_wrapped <- function(...) {
      tryCatch(
        {
          out <- callback(...)
          if (is.logical(out) && length(out) == 1 && !is.na(out)) {
            out
          } else {
            rlang::error_cnd(message = "Callback returned a value different from TRUE or FALSE")
          }
        },
        error = function(e) e,
        interrupt = function(e) e
      )
    }
  } else {
    callback_wrapped <- NULL
  }


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maximal_cliques_callback_closure,
    graph,
    min_size,
    max_size,
    callback_wrapped
  )

  res
}

maximal_cliques_count_impl <- function(
  graph,
  min_size = 0,
  max_size = 0
) {
  # Argument checks
  ensure_igraph(graph)
  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maximal_cliques_count,
    graph,
    min_size,
    max_size
  )

  res
}

maximal_cliques_file_impl <- function(
  graph,
  res,
  min_size = 0,
  max_size = 0
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(res)

  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maximal_cliques_file,
    graph,
    res,
    min_size,
    max_size
  )

  res
}

maximal_cliques_hist_impl <- function(
  graph,
  min_size = 0,
  max_size = 0
) {
  # Argument checks
  ensure_igraph(graph)
  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maximal_cliques_hist,
    graph,
    min_size,
    max_size
  )

  res
}

maximal_cliques_impl <- function(
  graph,
  min_size = 0,
  max_size = 0
) {
  # Argument checks
  ensure_igraph(graph)
  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maximal_cliques,
    graph,
    min_size,
    max_size
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs_list(graph, res)
  }
  res
}

maximal_cliques_subset_impl <- function(
  graph,
  subset,
  outfile = NULL,
  min_size = 0,
  max_size = 0,
  details = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  subset <- as_igraph_vs(graph, subset)
  subset <- subset - 1
  if (!is.null(outfile)) {
    check_string(outfile)

  }
  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maximal_cliques_subset,
    graph,
    subset,
    outfile,
    min_size,
    max_size
  )
  if (igraph_opt("return.vs.es")) {
    res$res <- create_vs_list(graph, res$res)
  }
  if (!details) {
    res <- res$res
  }
  res
}

# ==== independent-vertex-sets ====

independence_number_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_independence_number,
    graph
  )

  res
}

independent_vertex_sets_impl <- function(
  graph,
  min_size = 0,
  max_size = 0
) {
  # Argument checks
  ensure_igraph(graph)
  min_size <- as.numeric(min_size)
  max_size <- as.numeric(max_size)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_independent_vertex_sets,
    graph,
    min_size,
    max_size
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs_list(graph, res)
  }
  res
}

is_independent_vertex_set_impl <- function(
  graph,
  candidate
) {
  # Argument checks
  ensure_igraph(graph)
  candidate <- as_igraph_vs(graph, candidate)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_independent_vertex_set,
    graph,
    candidate - 1
  )

  res
}

largest_independent_vertex_sets_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_largest_independent_vertex_sets,
    graph
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs_list(graph, res)
  }
  res
}

maximal_independent_vertex_sets_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maximal_independent_vertex_sets,
    graph
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs_list(graph, res)
  }
  res
}

# ==== weighted-cliques ====

largest_weighted_cliques_impl <- function(
  graph,
  vertex_weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(vertex_weights) && "weight" %in% vertex_attr_names(graph)) {
    vertex_weights <- V(graph)$weight
  }
  if (!is.null(vertex_weights) && !all(is.na(vertex_weights))) {
    vertex_weights <- as.numeric(vertex_weights)
  } else {
    vertex_weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_largest_weighted_cliques,
    graph,
    vertex_weights
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs_list(graph, res)
  }
  res
}

weighted_clique_number_impl <- function(
  graph,
  vertex_weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(vertex_weights) && "weight" %in% vertex_attr_names(graph)) {
    vertex_weights <- V(graph)$weight
  }
  if (!is.null(vertex_weights) && !all(is.na(vertex_weights))) {
    vertex_weights <- as.numeric(vertex_weights)
  } else {
    vertex_weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_weighted_clique_number,
    graph,
    vertex_weights
  )

  res
}

weighted_cliques_impl <- function(
  graph,
  vertex_weights = NULL,
  min_weight = 0,
  max_weight = 0,
  maximal = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(vertex_weights) && "weight" %in% vertex_attr_names(graph)) {
    vertex_weights <- V(graph)$weight
  }
  if (!is.null(vertex_weights) && !all(is.na(vertex_weights))) {
    vertex_weights <- as.numeric(vertex_weights)
  } else {
    vertex_weights <- NULL
  }
  min_weight <- as.numeric(min_weight)
  max_weight <- as.numeric(max_weight)
  maximal <- as.logical(maximal)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_weighted_cliques,
    graph,
    vertex_weights,
    min_weight,
    max_weight,
    maximal
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs_list(graph, res)
  }
  res
}
