# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== invoking-the-status-handler ====

status_impl <- function(
  message
) {
  # Argument checks


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_status,
    message
  )

  res
}
