# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== common-functions-related-to-community-detection ====

community_optimal_modularity_impl <- function(
  graph,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_optimal_modularity,
    graph,
    weights
  )

  res
}

community_to_membership_impl <- function(
  merges,
  nodes,
  steps
) {
  # Argument checks
  nodes <- as.numeric(nodes)
  steps <- as.numeric(steps)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_to_membership,
    merges,
    nodes,
    steps
  )

  res
}

compare_communities_impl <- function(
  comm1,
  comm2,
  method = c("vi", "nmi", "split.join", "rand", "adjusted.rand")
) {
  # Argument checks
  comm1 <- as.numeric(comm1)
  comm2 <- as.numeric(comm2)
  method <- switch_igraph_arg(
    method,
    "vi" = 0L,
    "nmi" = 1L,
    "split.join" = 2L,
    "rand" = 3L,
    "adjusted.rand" = 4L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_compare_communities,
    comm1,
    comm2,
    method
  )

  res
}

modularity_impl <- function(
  graph,
  membership,
  weights = NULL,
  resolution = 1.0,
  directed = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  membership <- as.numeric(membership)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  resolution <- as.numeric(resolution)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_modularity,
    graph,
    membership,
    weights,
    resolution,
    directed
  )

  res
}

modularity_matrix_impl <- function(
  graph,
  weights = NULL,
  resolution = 1.0,
  directed = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  resolution <- as.numeric(resolution)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_modularity_matrix,
    graph,
    weights,
    resolution,
    directed
  )

  res
}

reindex_membership_impl <- function(
  membership
) {
  # Argument checks
  membership <- as.numeric(membership)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_reindex_membership,
    membership
  )

  res
}

split_join_distance_impl <- function(
  comm1,
  comm2
) {
  # Argument checks
  comm1 <- as.numeric(comm1)
  comm2 <- as.numeric(comm2)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_split_join_distance,
    comm1,
    comm2
  )

  res
}

# ==== community-detection-based-on-statistical-mechanics ====

community_spinglass_impl <- function(
  graph,
  weights = NULL,
  spins = 25,
  parupdate = FALSE,
  starttemp = 1,
  stoptemp = 0.01,
  coolfact = 0.99,
  update_rule = c("config", "simple"),
  gamma = 1.0,
  implementation = c("orig", "neg"),
  lambda = 1.0
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  spins <- as.numeric(spins)
  parupdate <- as.logical(parupdate)
  starttemp <- as.numeric(starttemp)
  stoptemp <- as.numeric(stoptemp)
  coolfact <- as.numeric(coolfact)
  update_rule <- switch_igraph_arg(update_rule, "simple" = 0L, "config" = 1L)
  gamma <- as.numeric(gamma)
  implementation <- switch_igraph_arg(implementation, "orig" = 0L, "neg" = 1L)
  lambda <- as.numeric(lambda)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_spinglass,
    graph,
    weights,
    spins,
    parupdate,
    starttemp,
    stoptemp,
    coolfact,
    update_rule,
    gamma,
    implementation,
    lambda
  )

  res
}

community_spinglass_single_impl <- function(
  graph,
  weights = NULL,
  vertex,
  spins = 25,
  update_rule = c("config", "simple"),
  gamma = 1.0
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  vertex <- as.numeric(vertex)
  spins <- as.numeric(spins)
  update_rule <- switch_igraph_arg(update_rule, "simple" = 0L, "config" = 1L)
  gamma <- as.numeric(gamma)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_spinglass_single,
    graph,
    weights,
    vertex,
    spins,
    update_rule,
    gamma
  )

  res
}

# ==== community-structure-based-on-eigenvectors-of-matrices ====

community_leading_eigenvector_callback_closure_impl <- function(
  graph,
  weights = NULL,
  membership = NULL,
  steps = -1,
  options = arpack_defaults(),
  start = FALSE,
  callback = NULL,
  extra = NULL,
  env = parent.frame(),
  env_arp = environment(igraph.i.levc.arp)
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  if (!is.null(membership)) {
    membership <- as.numeric(membership)
  }
  steps <- as.numeric(steps)
  options <- modify_list(arpack_defaults(), options)
  start <- as.logical(start)
  if (!is.null(callback)) {
    if (!is.function(callback)) {
      cli::cli_abort("{.arg callback} must be a function")
    }
    callback_wrapped <- function(...) {
      tryCatch(
        {
          out <- callback(...)
          if (is.logical(out) && length(out) == 1 && !is.na(out)) {
            out
          } else {
            rlang::error_cnd(message = "Callback returned a value different from TRUE or FALSE")
          }
        },
        error = function(e) e,
        interrupt = function(e) e
      )
    }
  } else {
    callback_wrapped <- NULL
  }


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_leading_eigenvector_callback_closure,
    graph,
    weights,
    membership,
    steps,
    options,
    start,
    callback_wrapped,
    extra,
    env,
    env_arp
  )

  class(res) <- "igraph.eigenc"
  res
}

le_community_to_membership_impl <- function(
  merges,
  steps,
  membership
) {
  # Argument checks
  steps <- as.numeric(steps)
  membership <- as.numeric(membership)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_le_community_to_membership,
    merges,
    steps,
    membership
  )

  res
}

# ==== community-structure-based-on-the-optimization-of-modularity ====

community_fastgreedy_impl <- function(
  graph,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_fastgreedy,
    graph,
    weights
  )

  res
}

community_leiden_impl <- function(
  graph,
  weights = NULL,
  vertex_weights = NULL,
  resolution,
  beta = 0.01,
  start,
  n_iterations = 2,
  membership = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  if (is.null(vertex_weights) && "weight" %in% vertex_attr_names(graph)) {
    vertex_weights <- V(graph)$weight
  }
  if (!is.null(vertex_weights) && !all(is.na(vertex_weights))) {
    vertex_weights <- as.numeric(vertex_weights)
  } else {
    vertex_weights <- NULL
  }
  resolution <- as.numeric(resolution)
  beta <- as.numeric(beta)
  start <- as.logical(start)
  n_iterations <- as.numeric(n_iterations)
  if (!is.null(membership)) {
    membership <- as.numeric(membership)
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_leiden,
    graph,
    weights,
    vertex_weights,
    resolution,
    beta,
    start,
    n_iterations,
    membership
  )

  res
}

community_multilevel_impl <- function(
  graph,
  weights = NULL,
  resolution = 1.0
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  resolution <- as.numeric(resolution)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_multilevel,
    graph,
    weights,
    resolution
  )

  res
}

# ==== edge-betweenness-based-community-detection ====

community_eb_get_merges_impl <- function(
  graph,
  directed,
  edges,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  directed <- as.logical(directed)
  edges <- as_igraph_es(graph, edges)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_eb_get_merges,
    graph,
    directed,
    edges - 1,
    weights
  )

  res
}

community_edge_betweenness_impl <- function(
  graph,
  directed = TRUE,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  directed <- as.logical(directed)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_edge_betweenness,
    graph,
    directed,
    weights
  )

  res
}

# ==== fluid-communities ====

community_fluid_communities_impl <- function(
  graph,
  no_of_communities
) {
  # Argument checks
  ensure_igraph(graph)
  no_of_communities <- as.numeric(no_of_communities)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_fluid_communities,
    graph,
    no_of_communities
  )

  res
}

# ==== infomap-algorithm ====

community_infomap_impl <- function(
  graph,
  e_weights = NULL,
  v_weights = NULL,
  nb_trials = 10
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(e_weights) && "weight" %in% edge_attr_names(graph)) {
    e_weights <- E(graph)$weight
  }
  if (!is.null(e_weights) && !all(is.na(e_weights))) {
    e_weights <- as.numeric(e_weights)
  } else {
    e_weights <- NULL
  }
  if (is.null(v_weights) && "weight" %in% vertex_attr_names(graph)) {
    v_weights <- V(graph)$weight
  }
  if (!is.null(v_weights) && !all(is.na(v_weights))) {
    v_weights <- as.numeric(v_weights)
  } else {
    v_weights <- NULL
  }
  nb_trials <- as.numeric(nb_trials)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_infomap,
    graph,
    e_weights,
    v_weights,
    nb_trials
  )

  res
}

# ==== label-propagation ====

community_label_propagation_impl <- function(
  graph,
  mode = c("all", "out", "in", "total"),
  weights = NULL,
  initial = NULL,
  fixed = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  if (!is.null(initial)) {
    initial <- as.numeric(initial) - 1
  }
  if (!is.null(fixed)) {
    fixed <- as.logical(fixed)
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_label_propagation,
    graph,
    mode,
    weights,
    initial,
    fixed
  )

  res
}

# ==== voronoi-communities ====

community_voronoi_impl <- function(
  graph,
  lengths = NULL,
  weights = NULL,
  mode = c("out", "in", "all", "total"),
  radius = -1
) {
  # Argument checks
  ensure_igraph(graph)
  if (!is.null(lengths) && !all(is.na(lengths))) {
    lengths <- as.numeric(lengths)
  } else {
    lengths <- NULL
  }
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  radius <- as.numeric(radius)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_voronoi,
    graph,
    lengths,
    weights,
    mode,
    radius
  )
  if (igraph_opt("return.vs.es")) {
    res$generators <- create_vs(graph, res$generators)
  }
  res
}

# ==== walktrap-community-structure-based-on-random-walks ====

community_walktrap_impl <- function(
  graph,
  weights = NULL,
  steps = 4
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  steps <- as.numeric(steps)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_community_walktrap,
    graph,
    weights,
    steps
  )

  res
}
