# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off
# jarl-ignore-file unused_function: irrelevant for _impl functions

# ==== drl-layout-generator ====

layout_drl_3d_impl <- function(
  graph,
  res,
  use_seed = FALSE,
  options = drl_defaults$default,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  res[] <- as.numeric(res)
  use_seed <- as.logical(use_seed)
  options <- modify_list(drl_defaults$default, options)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_drl_3d,
    graph,
    res,
    use_seed,
    options,
    weights
  )

  res
}

layout_drl_impl <- function(
  graph,
  res,
  use_seed = FALSE,
  options = drl_defaults$default,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  res[] <- as.numeric(res)
  use_seed <- as.logical(use_seed)
  options <- modify_list(drl_defaults$default, options)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_drl,
    graph,
    res,
    use_seed,
    options,
    weights
  )

  res
}

# ==== layouts-for-trees-and-acyclic-graphs ====

layout_reingold_tilford_circular_impl <- function(
  graph,
  mode = c("out", "in", "all", "total"),
  roots = NULL,
  rootlevel = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  if (!is.null(roots)) {
    roots <- as_igraph_vs(graph, roots)
    roots <- roots - 1
  }
  if (!is.null(rootlevel)) {
    rootlevel <- as.numeric(rootlevel)
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_reingold_tilford_circular,
    graph,
    mode,
    roots,
    rootlevel
  )

  res
}

layout_reingold_tilford_impl <- function(
  graph,
  mode = c("out", "in", "all", "total"),
  roots = NULL,
  rootlevel = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  if (!is.null(roots)) {
    roots <- as_igraph_vs(graph, roots)
    roots <- roots - 1
  }
  if (!is.null(rootlevel)) {
    rootlevel <- as.numeric(rootlevel)
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_reingold_tilford,
    graph,
    mode,
    roots,
    rootlevel
  )

  res
}

layout_sugiyama_impl <- function(
  graph,
  layers = NULL,
  hgap = 1,
  vgap = 1,
  maxiter = 100,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (!is.null(layers)) {
    layers <- as.numeric(layers) - 1
  }
  hgap <- as.numeric(hgap)
  vgap <- as.numeric(vgap)
  maxiter <- as.numeric(maxiter)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_sugiyama,
    graph,
    layers,
    hgap,
    vgap,
    maxiter,
    weights
  )

  res
}

layout_umap_compute_weights_impl <- function(
  graph,
  distances,
  weights
) {
  # Argument checks
  ensure_igraph(graph)
  distances <- as.numeric(distances)
  weights <- as.numeric(weights)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_umap_compute_weights,
    graph,
    distances,
    weights
  )

  res
}

layout_umap_impl <- function(
  graph,
  res,
  use_seed = FALSE,
  distances = NULL,
  min_dist = 0.0,
  epochs = 200,
  distances_are_weights = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  res[] <- as.numeric(res)
  use_seed <- as.logical(use_seed)
  if (!is.null(distances)) {
    distances <- as.numeric(distances)
  }
  min_dist <- as.numeric(min_dist)
  epochs <- as.numeric(epochs)
  distances_are_weights <- as.logical(distances_are_weights)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_umap,
    graph,
    res,
    use_seed,
    distances,
    min_dist,
    epochs,
    distances_are_weights
  )

  res
}

roots_for_tree_layout_impl <- function(
  graph,
  mode = c("out", "in", "all", "total"),
  heuristic
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_roots_for_tree_layout,
    graph,
    mode,
    heuristic
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_vs(graph, res)
  }
  res
}

# ==== pp-layouts ====

layout_align_impl <- function(
  graph,
  layout
) {
  # Argument checks
  ensure_igraph(graph)
  layout[] <- as.numeric(layout)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_align,
    graph,
    layout
  )

  res
}

layout_merge_dla_impl <- function(
  graphs,
  coords
) {
  # Argument checks
  if (!is.list(graphs)) {
    cli::cli_abort("{.arg graphs} must be a list of igraph objects")
  }
  graphs <- lapply(graphs, function(g) {
    if (!inherits(g, "igraph")) {
      cli::cli_abort("{.arg graphs} must be a list of igraph objects")
    }
    g
  })
  if (!is.list(coords)) {
    cli::cli_abort("{.arg coords} must be a list of matrices")
  }
  coords <- lapply(coords, function(m) {
    if (!is.matrix(m)) {
      cli::cli_abort("{.arg coords} must be a list of matrices")
    }
    m[] <- as.numeric(m)
    m
  })

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_merge_dla,
    graphs,
    coords
  )

  res
}

# ==== three-d-layout-generators ====

layout_fruchterman_reingold_3d_impl <- function(
  graph,
  coords = NULL,
  use_seed = FALSE,
  niter = 500,
  start_temp = sqrt(vcount(graph)),
  weights = NULL,
  minx = NULL,
  maxx = NULL,
  miny = NULL,
  maxy = NULL,
  minz = NULL,
  maxz = NULL,
  coolexp = NULL,
  maxdelta = NULL,
  area = NULL,
  repulserad = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (!is.null(coords)) {
    coords[] <- as.numeric(coords)
  }
  use_seed <- as.logical(use_seed)
  niter <- as.numeric(niter)
  start_temp <- as.numeric(start_temp)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  if (!is.null(minx)) {
    minx <- as.numeric(minx)
  }
  if (!is.null(maxx)) {
    maxx <- as.numeric(maxx)
  }
  if (!is.null(miny)) {
    miny <- as.numeric(miny)
  }
  if (!is.null(maxy)) {
    maxy <- as.numeric(maxy)
  }
  if (!is.null(minz)) {
    minz <- as.numeric(minz)
  }
  if (!is.null(maxz)) {
    maxz <- as.numeric(maxz)
  }
  if (!missing(coolexp)) { warning("Argument `coolexp' is deprecated and has no effect") }
  if (!missing(maxdelta)) { warning("Argument `maxdelta' is deprecated and has no effect") }
  if (!missing(area)) { warning("Argument `area' is deprecated and has no effect") }
  if (!missing(repulserad)) { warning("Argument `repulserad' is deprecated and has no effect") }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_fruchterman_reingold_3d,
    graph,
    coords,
    use_seed,
    niter,
    start_temp,
    weights,
    minx,
    maxx,
    miny,
    maxy,
    minz,
    maxz
  )

  res
}

layout_grid_3d_impl <- function(
  graph,
  width = 0,
  height = 0
) {
  # Argument checks
  ensure_igraph(graph)
  width <- as.numeric(width)
  height <- as.numeric(height)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_grid_3d,
    graph,
    width,
    height
  )

  res
}

layout_kamada_kawai_3d_impl <- function(
  graph,
  coords,
  use_seed = FALSE,
  maxiter = 500,
  epsilon = 0.0,
  kkconst = vcount(graph),
  weights = NULL,
  minx = NULL,
  maxx = NULL,
  miny = NULL,
  maxy = NULL,
  minz = NULL,
  maxz = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  coords[] <- as.numeric(coords)
  use_seed <- as.logical(use_seed)
  maxiter <- as.numeric(maxiter)
  epsilon <- as.numeric(epsilon)
  kkconst <- as.numeric(kkconst)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  if (!is.null(minx)) {
    minx <- as.numeric(minx)
  }
  if (!is.null(maxx)) {
    maxx <- as.numeric(maxx)
  }
  if (!is.null(miny)) {
    miny <- as.numeric(miny)
  }
  if (!is.null(maxy)) {
    maxy <- as.numeric(maxy)
  }
  if (!is.null(minz)) {
    minz <- as.numeric(minz)
  }
  if (!is.null(maxz)) {
    maxz <- as.numeric(maxz)
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_kamada_kawai_3d,
    graph,
    coords,
    use_seed,
    maxiter,
    epsilon,
    kkconst,
    weights,
    minx,
    maxx,
    miny,
    maxy,
    minz,
    maxz
  )

  res
}

layout_random_3d_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_random_3d,
    graph
  )

  res
}

layout_sphere_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_sphere,
    graph
  )

  res
}

layout_umap_3d_impl <- function(
  graph,
  res,
  use_seed = FALSE,
  distances = NULL,
  min_dist = 0.0,
  epochs = 200,
  distances_are_weights = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  res[] <- as.numeric(res)
  use_seed <- as.logical(use_seed)
  if (!is.null(distances)) {
    distances <- as.numeric(distances)
  }
  min_dist <- as.numeric(min_dist)
  epochs <- as.numeric(epochs)
  distances_are_weights <- as.logical(distances_are_weights)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_umap_3d,
    graph,
    res,
    use_seed,
    distances,
    min_dist,
    epochs,
    distances_are_weights
  )

  res
}

# ==== two-d-layout-generators ====

layout_bipartite_impl <- function(
  graph,
  types,
  hgap = 1,
  vgap = 1,
  maxiter = 100
) {
  # Argument checks
  ensure_igraph(graph)
  types <- handle_vertex_type_arg(types, graph)
  hgap <- as.numeric(hgap)
  vgap <- as.numeric(vgap)
  maxiter <- as.numeric(maxiter)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_bipartite,
    graph,
    types,
    hgap,
    vgap,
    maxiter
  )

  res
}

layout_circle_impl <- function(
  graph,
  order = V(graph)
) {
  # Argument checks
  ensure_igraph(graph)
  order <- as_igraph_vs(graph, order)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_circle,
    graph,
    order - 1
  )

  res
}

layout_davidson_harel_impl <- function(
  graph,
  res = matrix(),
  use_seed = FALSE,
  maxiter = 10,
  fineiter = max(10, log2(vcount(graph))),
  cool_fact = 0.75,
  weight_node_dist = 1.0,
  weight_border = 0.0,
  weight_edge_lengths = edge_density(graph) / 10,
  weight_edge_crossings = 1.0 - sqrt(edge_density(graph)),
  weight_node_edge_dist = 0.2 * (1 - edge_density(graph))
) {
  # Argument checks
  ensure_igraph(graph)
  res[] <- as.numeric(res)
  use_seed <- as.logical(use_seed)
  maxiter <- as.numeric(maxiter)
  fineiter <- as.numeric(fineiter)
  cool_fact <- as.numeric(cool_fact)
  weight_node_dist <- as.numeric(weight_node_dist)
  weight_border <- as.numeric(weight_border)
  weight_edge_lengths <- as.numeric(weight_edge_lengths)
  weight_edge_crossings <- as.numeric(weight_edge_crossings)
  weight_node_edge_dist <- as.numeric(weight_node_edge_dist)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_davidson_harel,
    graph,
    res,
    use_seed,
    maxiter,
    fineiter,
    cool_fact,
    weight_node_dist,
    weight_border,
    weight_edge_lengths,
    weight_edge_crossings,
    weight_node_edge_dist
  )

  res
}

layout_fruchterman_reingold_impl <- function(
  graph,
  coords = NULL,
  use_seed = FALSE,
  niter = 500,
  start_temp = sqrt(vcount(graph)),
  grid = c("auto", "grid", "nogrid"),
  weights = NULL,
  minx = NULL,
  maxx = NULL,
  miny = NULL,
  maxy = NULL,
  coolexp = NULL,
  maxdelta = NULL,
  area = NULL,
  repulserad = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (!is.null(coords)) {
    coords[] <- as.numeric(coords)
  }
  use_seed <- as.logical(use_seed)
  niter <- as.numeric(niter)
  start_temp <- as.numeric(start_temp)
  grid <- switch_igraph_arg(grid, "grid" = 0L, "nogrid" = 1L, "auto" = 2L)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  if (!is.null(minx)) {
    minx <- as.numeric(minx)
  }
  if (!is.null(maxx)) {
    maxx <- as.numeric(maxx)
  }
  if (!is.null(miny)) {
    miny <- as.numeric(miny)
  }
  if (!is.null(maxy)) {
    maxy <- as.numeric(maxy)
  }
  if (!missing(coolexp)) { warning("Argument `coolexp' is deprecated and has no effect") }
  if (!missing(maxdelta)) { warning("Argument `maxdelta' is deprecated and has no effect") }
  if (!missing(area)) { warning("Argument `area' is deprecated and has no effect") }
  if (!missing(repulserad)) { warning("Argument `repulserad' is deprecated and has no effect") }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_fruchterman_reingold,
    graph,
    coords,
    use_seed,
    niter,
    start_temp,
    grid,
    weights,
    minx,
    maxx,
    miny,
    maxy
  )

  res
}

layout_gem_impl <- function(
  graph,
  res = matrix(),
  use_seed = FALSE,
  maxiter = 40,
  temp_max = vcount(graph),
  temp_min = 1,
  temp_init = sqrt(vcount(graph))
) {
  # Argument checks
  ensure_igraph(graph)
  res[] <- as.numeric(res)
  use_seed <- as.logical(use_seed)
  maxiter <- as.numeric(maxiter)
  temp_max <- as.numeric(temp_max)
  temp_min <- as.numeric(temp_min)
  temp_init <- as.numeric(temp_init)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_gem,
    graph,
    res,
    use_seed,
    maxiter,
    temp_max,
    temp_min,
    temp_init
  )

  res
}

layout_graphopt_impl <- function(
  graph,
  res,
  niter = 500,
  node_charge = 0.001,
  node_mass = 30,
  spring_length = 0,
  spring_constant = 1,
  max_sa_movement = 5,
  use_seed = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  res[] <- as.numeric(res)
  niter <- as.numeric(niter)
  node_charge <- as.numeric(node_charge)
  node_mass <- as.numeric(node_mass)
  spring_length <- as.numeric(spring_length)
  spring_constant <- as.numeric(spring_constant)
  max_sa_movement <- as.numeric(max_sa_movement)
  use_seed <- as.logical(use_seed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_graphopt,
    graph,
    res,
    niter,
    node_charge,
    node_mass,
    spring_length,
    spring_constant,
    max_sa_movement,
    use_seed
  )

  res
}

layout_grid_impl <- function(
  graph,
  width = 0
) {
  # Argument checks
  ensure_igraph(graph)
  width <- as.numeric(width)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_grid,
    graph,
    width
  )

  res
}

layout_kamada_kawai_impl <- function(
  graph,
  coords,
  use_seed = FALSE,
  maxiter = 500,
  epsilon = 0.0,
  kkconst = vcount(graph),
  weights = NULL,
  minx = NULL,
  maxx = NULL,
  miny = NULL,
  maxy = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  coords[] <- as.numeric(coords)
  use_seed <- as.logical(use_seed)
  maxiter <- as.numeric(maxiter)
  epsilon <- as.numeric(epsilon)
  kkconst <- as.numeric(kkconst)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  if (!is.null(minx)) {
    minx <- as.numeric(minx)
  }
  if (!is.null(maxx)) {
    maxx <- as.numeric(maxx)
  }
  if (!is.null(miny)) {
    miny <- as.numeric(miny)
  }
  if (!is.null(maxy)) {
    maxy <- as.numeric(maxy)
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_kamada_kawai,
    graph,
    coords,
    use_seed,
    maxiter,
    epsilon,
    kkconst,
    weights,
    minx,
    maxx,
    miny,
    maxy
  )

  res
}

layout_lgl_impl <- function(
  graph,
  maxiter = 150,
  maxdelta = vcount(graph),
  area = vcount(graph)^2,
  coolexp = 1.5,
  repulserad = vcount(graph)^3,
  cellsize = vcount(graph),
  root = -1
) {
  # Argument checks
  ensure_igraph(graph)
  maxiter <- as.numeric(maxiter)
  maxdelta <- as.numeric(maxdelta)
  area <- as.numeric(area)
  coolexp <- as.numeric(coolexp)
  repulserad <- as.numeric(repulserad)
  cellsize <- as.numeric(cellsize)
  root <- as.numeric(root)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_lgl,
    graph,
    maxiter,
    maxdelta,
    area,
    coolexp,
    repulserad,
    cellsize,
    root
  )

  res
}

layout_mds_impl <- function(
  graph,
  dist = NULL,
  dim = 2
) {
  # Argument checks
  ensure_igraph(graph)
  if (!is.null(dist)) {
    dist[] <- as.numeric(dist)
  }
  dim <- as.numeric(dim)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_mds,
    graph,
    dist,
    dim
  )

  res
}

layout_random_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_random,
    graph
  )

  res
}

layout_star_impl <- function(
  graph,
  center = V(graph)[1],
  order = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  center <- as_igraph_vs(graph, center)
  if (length(center) != 1) {
    cli::cli_abort(
      "{.arg center} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (!is.null(order)) {
    order <- as.numeric(order) - 1
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_layout_star,
    graph,
    center - 1,
    order
  )

  res
}
