# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== binary-formats ====

read_graph_graphdb_impl <- function(
  instream,
  directed = FALSE
) {
  # Argument checks
  check_string(instream)

  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_graphdb,
    instream,
    directed
  )

  res
}

# ==== gml-format ====

read_graph_gml_impl <- function(
  instream
) {
  # Argument checks
  check_string(instream)


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_gml,
    instream
  )

  res
}

write_graph_gml_impl <- function(
  graph,
  outstream,
  options = c("default", "encode_only_quot"),
  id,
  creator = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)

  options <- switch_igraph_arg(options, "default" = 0L, "encode_only_quot" = 1L)
  id <- as.numeric(id)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_gml,
    graph,
    outstream,
    options,
    id,
    creator
  )

  res
}

# ==== graphml-format ====

read_graph_graphml_impl <- function(
  instream,
  index = 0
) {
  # Argument checks
  check_string(instream)

  index <- as.numeric(index)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_graphml,
    instream,
    index
  )

  res
}

write_graph_graphml_impl <- function(
  graph,
  outstream,
  prefixattr = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)

  prefixattr <- as.logical(prefixattr)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_graphml,
    graph,
    outstream,
    prefixattr
  )

  res
}

# ==== graphviz-format ====

write_graph_dot_impl <- function(
  graph,
  outstream
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_dot,
    graph,
    outstream
  )

  res
}

# ==== leda-format ====

write_graph_leda_impl <- function(
  graph,
  outstream,
  names = "name",
  weights = "weight"
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_leda,
    graph,
    outstream,
    names,
    weights
  )

  res
}

# ==== pajek-format ====

read_graph_pajek_impl <- function(
  instream
) {
  # Argument checks
  check_string(instream)


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_pajek,
    instream
  )

  res
}

write_graph_pajek_impl <- function(
  graph,
  outstream
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_pajek,
    graph,
    outstream
  )

  res
}

# ==== simple-edge-list-and-similar-formats ====

read_graph_dimacs_flow_impl <- function(
  instream,
  directed = TRUE
) {
  # Argument checks
  check_string(instream)

  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_dimacs_flow,
    instream,
    directed
  )

  res
}

read_graph_edgelist_impl <- function(
  instream,
  n = 0,
  directed = TRUE
) {
  # Argument checks
  check_string(instream)

  n <- as.numeric(n)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_edgelist,
    instream,
    n,
    directed
  )

  res
}

read_graph_lgl_impl <- function(
  instream,
  names = TRUE,
  weights = TRUE,
  directed = TRUE
) {
  # Argument checks
  check_string(instream)

  names <- as.logical(names)
  weights <- switch_igraph_arg(weights, "no" = 0L, "yes" = 1L, "auto" = 2L)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_lgl,
    instream,
    names,
    weights,
    directed
  )

  res
}

read_graph_ncol_impl <- function(
  instream,
  predefnames = NULL,
  names = TRUE,
  weights = TRUE,
  directed = TRUE
) {
  # Argument checks
  check_string(instream)

  names <- as.logical(names)
  weights <- switch_igraph_arg(weights, "no" = 0L, "yes" = 1L, "auto" = 2L)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_ncol,
    instream,
    predefnames,
    names,
    weights,
    directed
  )

  res
}

write_graph_dimacs_flow_impl <- function(
  graph,
  outstream,
  source = 0,
  target = 0,
  capacity
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)

  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  capacity <- as.numeric(capacity)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_dimacs_flow,
    graph,
    outstream,
    source - 1,
    target - 1,
    capacity
  )

  res
}

write_graph_edgelist_impl <- function(
  graph,
  outstream
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_edgelist,
    graph,
    outstream
  )

  res
}

write_graph_lgl_impl <- function(
  graph,
  outstream,
  names = "name",
  weights = "weight",
  isolates = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)

  isolates <- as.logical(isolates)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_lgl,
    graph,
    outstream,
    names,
    weights,
    isolates
  )

  res
}

write_graph_ncol_impl <- function(
  graph,
  outstream,
  names = "name",
  weights = "weight"
) {
  # Argument checks
  ensure_igraph(graph)
  check_string(outstream)


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_write_graph_ncol,
    graph,
    outstream,
    names,
    weights
  )

  res
}

# ==== ucinets-dl-file-format ====

read_graph_dl_impl <- function(
  instream,
  directed = TRUE
) {
  # Argument checks
  check_string(instream)

  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_read_graph_dl,
    instream,
    directed
  )

  res
}
