# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== breadth-first-search ====

bfs_closure_impl <- function(
  graph,
  root,
  roots = NULL,
  mode = c("out", "in", "all", "total"),
  unreachable,
  restricted = NULL,
  callback
) {
  # Argument checks
  ensure_igraph(graph)
  root <- as_igraph_vs(graph, root)
  if (length(root) != 1) {
    cli::cli_abort(
      "{.arg root} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (!is.null(roots)) {
    roots <- as_igraph_vs(graph, roots)
    roots <- roots - 1
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  unreachable <- as.logical(unreachable)
  if (!is.null(restricted)) {
    restricted <- as_igraph_vs(graph, restricted)
    restricted <- restricted - 1
  }
  if (!is.null(callback)) {
    if (!is.function(callback)) {
      cli::cli_abort("{.arg callback} must be a function")
    }
    callback_wrapped <- function(...) {
      tryCatch(
        {
          out <- callback(...)
          if (is.logical(out) && length(out) == 1 && !is.na(out)) {
            out
          } else {
            rlang::error_cnd(message = "Callback returned a value different from TRUE or FALSE")
          }
        },
        error = function(e) e,
        interrupt = function(e) e
      )
    }
  } else {
    callback_wrapped <- NULL
  }


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_bfs_closure,
    graph,
    root - 1,
    roots,
    mode,
    unreachable,
    restricted,
    callback_wrapped
  )
  if (igraph_opt("return.vs.es")) {
    res$order <- create_vs(graph, res$order)
  }
  res
}

bfs_simple_impl <- function(
  graph,
  root,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  root <- as_igraph_vs(graph, root)
  if (length(root) != 1) {
    cli::cli_abort(
      "{.arg root} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_bfs_simple,
    graph,
    root - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$order <- create_vs(graph, res$order)
  }
  res
}

# ==== depth-first-search ====

dfs_closure_impl <- function(
  graph,
  root,
  mode = c("out", "in", "all", "total"),
  unreachable,
  in_callback,
  out_callback
) {
  # Argument checks
  ensure_igraph(graph)
  root <- as_igraph_vs(graph, root)
  if (length(root) != 1) {
    cli::cli_abort(
      "{.arg root} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  unreachable <- as.logical(unreachable)
  if (!is.null(in_callback)) {
    if (!is.function(in_callback)) {
      cli::cli_abort("{.arg callback} must be a function")
    }
    in_callback_wrapped <- function(...) {
      tryCatch(
        {
          out <- in_callback(...)
          if (is.logical(out) && length(out) == 1 && !is.na(out)) {
            out
          } else {
            rlang::error_cnd(message = "Callback returned a value different from TRUE or FALSE")
          }
        },
        error = function(e) e,
        interrupt = function(e) e
      )
    }
  } else {
    in_callback_wrapped <- NULL
  }

  if (!is.null(out_callback)) {
    if (!is.function(out_callback)) {
      cli::cli_abort("{.arg callback} must be a function")
    }
    out_callback_wrapped <- function(...) {
      tryCatch(
        {
          out <- out_callback(...)
          if (is.logical(out) && length(out) == 1 && !is.na(out)) {
            out
          } else {
            rlang::error_cnd(message = "Callback returned a value different from TRUE or FALSE")
          }
        },
        error = function(e) e,
        interrupt = function(e) e
      )
    }
  } else {
    out_callback_wrapped <- NULL
  }


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_dfs_closure,
    graph,
    root - 1,
    mode,
    unreachable,
    in_callback_wrapped,
    out_callback_wrapped
  )
  if (igraph_opt("return.vs.es")) {
    res$order <- create_vs(graph, res$order)
  }
  if (igraph_opt("return.vs.es")) {
    res$order_out <- create_vs(graph, res$order_out)
  }
  res
}

# ==== random-walks ====

random_edge_walk_impl <- function(
  graph,
  weights = NULL,
  start,
  mode = c("out", "in", "all", "total"),
  steps,
  stuck = c("return", "error")
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  start <- as_igraph_vs(graph, start)
  if (length(start) != 1) {
    cli::cli_abort(
      "{.arg start} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  steps <- as.numeric(steps)
  stuck <- switch_igraph_arg(stuck, "error" = 0L, "return" = 1L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_random_edge_walk,
    graph,
    weights,
    start - 1,
    mode,
    steps,
    stuck
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_es(graph, res)
  }
  res
}

random_walk_impl <- function(
  graph,
  start,
  steps,
  weights = NULL,
  mode = c("out", "in", "all", "total"),
  stuck = c("return", "error")
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  start <- as_igraph_vs(graph, start)
  if (length(start) != 1) {
    cli::cli_abort(
      "{.arg start} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  steps <- as.numeric(steps)
  stuck <- switch_igraph_arg(stuck, "error" = 0L, "return" = 1L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_random_walk,
    graph,
    weights,
    start - 1,
    mode,
    steps,
    stuck
  )
  if (igraph_opt("return.vs.es")) {
    res$vertices <- create_vs(graph, res$vertices)
  }
  if (igraph_opt("return.vs.es")) {
    res$edges <- create_es(graph, res$edges)
  }
  res
}
