# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off
# jarl-ignore-file unused_function: irrelevant for _impl functions

# ==== cohesive-blocks ====

cohesive_blocks_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_cohesive_blocks,
    graph
  )
  if (igraph_opt("return.vs.es")) {
    res$blocks <- create_vs_list(graph, res$blocks)
  }
  class(res) <- "cohesiveBlocks"
  res
}

# ==== connectivity ====

edge_connectivity_impl <- function(
  graph,
  checks = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  checks <- as.logical(checks)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_edge_connectivity,
    graph,
    checks
  )

  res
}

st_edge_connectivity_impl <- function(
  graph,
  source,
  target
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_st_edge_connectivity,
    graph,
    source - 1,
    target - 1
  )

  res
}

st_vertex_connectivity_impl <- function(
  graph,
  source,
  target,
  neighbors = c("number_of_nodes", "error", "ignore", "negative")
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  neighbors <- switch_igraph_arg(
    neighbors,
    "error" = 0L,
    "number_of_nodes" = 1L,
    "ignore" = 2L,
    "negative" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_st_vertex_connectivity,
    graph,
    source - 1,
    target - 1,
    neighbors
  )

  res
}

vertex_connectivity_impl <- function(
  graph,
  checks = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  checks <- as.logical(checks)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_vertex_connectivity,
    graph,
    checks
  )

  res
}

# ==== cuts-and-minimum-cuts ====

all_st_cuts_impl <- function(
  graph,
  source,
  target
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_all_st_cuts,
    graph,
    source - 1,
    target - 1
  )
  if (igraph_opt("return.vs.es")) {
    res$cuts <- lapply(res$cuts, unsafe_create_es, graph = graph, es = E(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$partition1s <- create_vs_list(graph, res$partition1s)
  }
  res
}

all_st_mincuts_impl <- function(
  graph,
  source,
  target,
  capacity = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_all_st_mincuts,
    graph,
    source - 1,
    target - 1,
    capacity
  )
  if (igraph_opt("return.vs.es")) {
    res$cuts <- lapply(res$cuts, unsafe_create_es, graph = graph, es = E(graph))
  }
  if (igraph_opt("return.vs.es")) {
    res$partition1s <- create_vs_list(graph, res$partition1s)
  }
  res
}

gomory_hu_tree_impl <- function(
  graph,
  capacity = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_gomory_hu_tree,
    graph,
    capacity
  )

  res
}

mincut_impl <- function(
  graph,
  capacity = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_mincut,
    graph,
    capacity
  )
  if (igraph_opt("return.vs.es")) {
    res$partition1 <- create_vs(graph, res$partition1)
  }
  if (igraph_opt("return.vs.es")) {
    res$partition2 <- create_vs(graph, res$partition2)
  }
  if (igraph_opt("return.vs.es")) {
    res$cut <- create_es(graph, res$cut)
  }
  res
}

mincut_value_impl <- function(
  graph,
  capacity = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_mincut_value,
    graph,
    capacity
  )

  res
}

st_mincut_impl <- function(
  graph,
  source,
  target,
  capacity = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_st_mincut,
    graph,
    source - 1,
    target - 1,
    capacity
  )
  if (igraph_opt("return.vs.es")) {
    res$cut <- create_es(graph, res$cut)
  }
  if (igraph_opt("return.vs.es")) {
    res$partition1 <- create_vs(graph, res$partition1)
  }
  if (igraph_opt("return.vs.es")) {
    res$partition2 <- create_vs(graph, res$partition2)
  }
  res
}

st_mincut_value_impl <- function(
  graph,
  source,
  target,
  capacity = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_st_mincut_value,
    graph,
    source - 1,
    target - 1,
    capacity
  )

  res
}

# ==== edge-and-vertex-disjoint-paths ====

edge_disjoint_paths_impl <- function(
  graph,
  source,
  target
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_edge_disjoint_paths,
    graph,
    source - 1,
    target - 1
  )

  res
}

vertex_disjoint_paths_impl <- function(
  graph,
  source,
  target
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_vertex_disjoint_paths,
    graph,
    source - 1,
    target - 1
  )

  res
}

# ==== graph-adhesion-and-cohesion ====

adhesion_impl <- function(
  graph,
  checks = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  checks <- as.logical(checks)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_adhesion,
    graph,
    checks
  )

  res
}

cohesion_impl <- function(
  graph,
  checks = TRUE
) {
  # Argument checks
  ensure_igraph(graph)
  checks <- as.logical(checks)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_cohesion,
    graph,
    checks
  )

  res
}

# ==== maximum-flows ====

dominator_tree_impl <- function(
  graph,
  root,
  mode = c("out", "in", "all", "total")
) {
  # Argument checks
  ensure_igraph(graph)
  root <- as_igraph_vs(graph, root)
  if (length(root) != 1) {
    cli::cli_abort(
      "{.arg root} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_dominator_tree,
    graph,
    root - 1,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$leftout <- create_vs(graph, res$leftout)
  }
  res
}

maxflow_impl <- function(
  graph,
  source,
  target,
  capacity = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maxflow,
    graph,
    source - 1,
    target - 1,
    capacity
  )
  if (igraph_opt("return.vs.es")) {
    res$cut <- create_es(graph, res$cut)
  }
  if (igraph_opt("return.vs.es")) {
    res$partition1 <- create_vs(graph, res$partition1)
  }
  if (igraph_opt("return.vs.es")) {
    res$partition2 <- create_vs(graph, res$partition2)
  }
  res
}

maxflow_value_impl <- function(
  graph,
  source,
  target,
  capacity = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  source <- as_igraph_vs(graph, source)
  if (length(source) != 1) {
    cli::cli_abort(
      "{.arg source} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  target <- as_igraph_vs(graph, target)
  if (length(target) != 1) {
    cli::cli_abort(
      "{.arg target} must specify exactly one vertex",
      call = rlang::caller_env()
    )
  }
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_maxflow_value,
    graph,
    source - 1,
    target - 1,
    capacity
  )

  res
}

residual_graph_impl <- function(
  graph,
  capacity,
  flow
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }
  flow <- as.numeric(flow)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_residual_graph,
    graph,
    capacity,
    flow
  )

  res
}

reverse_residual_graph_impl <- function(
  graph,
  capacity,
  flow
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(capacity) && "capacity" %in% edge_attr_names(graph)) {
    capacity <- E(graph)$capacity
  }
  if (!is.null(capacity) && !all(is.na(capacity))) {
    capacity <- as.numeric(capacity)
  } else {
    capacity <- NULL
  }
  flow <- as.numeric(flow)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_reverse_residual_graph,
    graph,
    capacity,
    flow
  )

  res
}
