# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== performing-graphlet-decomposition ====

graphlets_candidate_basis_impl <- function(
  graph,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_graphlets_candidate_basis,
    graph,
    weights
  )
  if (igraph_opt("return.vs.es")) {
    res$cliques <- lapply(res$cliques, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  res
}

graphlets_impl <- function(
  graph,
  weights = NULL,
  niter = 1000
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  niter <- as.numeric(niter)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_graphlets,
    graph,
    weights,
    niter
  )
  if (igraph_opt("return.vs.es")) {
    res$cliques <- lapply(res$cliques, unsafe_create_vs, graph = graph, verts = V(graph))
  }
  res
}

graphlets_project_impl <- function(
  graph,
  weights = NULL,
  cliques,
  Muc,
  startMu = FALSE,
  niter = 1000
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }
  if (!is.null(cliques) && !is.list(cliques)) {
    cli::cli_abort(
      "{.arg cliques} must be a list or NULL",
      call = rlang::caller_env()
    )
  }
  Muc <- as.numeric(Muc)
  startMu <- as.logical(startMu)
  niter <- as.numeric(niter)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_graphlets_project,
    graph,
    weights,
    if (!is.null(cliques)) lapply(cliques, function(.x) .x - 1),
    Muc,
    startMu,
    niter
  )

  res
}
