# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off
# jarl-ignore-file unused_function: irrelevant for _impl functions

# ==== spanning-trees-and-forests ====

is_forest_impl <- function(
  graph,
  mode = c("out", "in", "all", "total"),
  details = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_forest,
    graph,
    mode
  )
  if (igraph_opt("return.vs.es")) {
    res$roots <- create_vs(graph, res$roots)
  }
  if (!details) {
    res <- res$res
  }
  res
}

is_tree_impl <- function(
  graph,
  mode = c("out", "in", "all", "total"),
  details = FALSE
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_tree,
    graph,
    mode
  )
  if (igraph_opt("return.vs.es") && vcount(graph) != 0) {
    res$root <- create_vs(graph, res$root)
  }
  if (!details) {
    res <- res$res
  }
  res
}

minimum_spanning_tree_impl <- function(
  graph,
  weights = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_minimum_spanning_tree,
    graph,
    weights
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_es(graph, res)
  }
  res
}

minimum_spanning_tree_prim_impl <- function(
  graph,
  weights
) {
  # Argument checks
  ensure_igraph(graph)
  if (is.null(weights) && "weight" %in% edge_attr_names(graph)) {
    weights <- E(graph)$weight
  }
  if (!is.null(weights) && !all(is.na(weights))) {
    weights <- as.numeric(weights)
  } else {
    weights <- NULL
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_minimum_spanning_tree_prim,
    graph,
    weights
  )

  res
}

minimum_spanning_tree_unweighted_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_minimum_spanning_tree_unweighted,
    graph
  )

  res
}

random_spanning_tree_impl <- function(
  graph,
  vid = 0
) {
  # Argument checks
  ensure_igraph(graph)
  if (!is.null(vid)) {
    vid <- as_igraph_vs(graph, vid)
    if (length(vid) != 1) {
      cli::cli_abort(
        "{.arg vid} must specify exactly one vertex",
        call = rlang::caller_env()
      )
    }
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_random_spanning_tree,
    graph,
    vid - 1
  )
  if (igraph_opt("return.vs.es")) {
    res <- create_es(graph, res)
  }
  res
}

to_prufer_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_to_prufer,
    graph
  )

  res
}

# ==== unfolding-a-graph-into-a-tree ====

unfold_tree_impl <- function(
  graph,
  mode = c("all", "out", "in", "total"),
  roots
) {
  # Argument checks
  ensure_igraph(graph)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  roots <- as.numeric(roots)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_unfold_tree,
    graph,
    mode,
    roots
  )

  res
}
