# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off
# jarl-ignore-file unused_function: irrelevant for _impl functions

# ==== bipartite-adjacency-matrices ====

biadjacency_impl <- function(
  incidence,
  directed = FALSE,
  mode = c("all", "out", "in", "total"),
  multiple = FALSE
) {
  # Argument checks
  incidence[] <- as.numeric(incidence)
  directed <- as.logical(directed)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  multiple <- as.logical(multiple)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_biadjacency,
    incidence,
    directed,
    mode,
    multiple
  )
  if (igraph_opt("add.vertex.names") && is_named(res$graph)) {
    names(res$types) <- vertex_attr(res$graph, "name", V(res$graph))
  }
  res
}

get_biadjacency_impl <- function(
  graph,
  types
) {
  # Argument checks
  ensure_igraph(graph)
  types <- handle_vertex_type_arg(types, graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_get_biadjacency,
    graph,
    types
  )

  res
}

# ==== create-two-mode-networks ====

bipartite_game_gnm_impl <- function(
  n1,
  n2,
  m,
  directed = FALSE,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  n1 <- as.numeric(n1)
  n2 <- as.numeric(n2)
  m <- as.numeric(m)
  directed <- as.logical(directed)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_bipartite_game_gnm,
    n1,
    n2,
    m,
    directed,
    mode
  )

  res
}

bipartite_game_gnp_impl <- function(
  n1,
  n2,
  p,
  directed = FALSE,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  n1 <- as.numeric(n1)
  n2 <- as.numeric(n2)
  p <- as.numeric(p)
  directed <- as.logical(directed)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_bipartite_game_gnp,
    n1,
    n2,
    p,
    directed,
    mode
  )

  res
}

bipartite_game_impl <- function(
  type,
  n1,
  n2,
  p = 0.0,
  m = 0,
  directed = FALSE,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  type <- switch_igraph_arg(type, "gnp" = 0L, "gnm" = 1L)
  n1 <- as.numeric(n1)
  n2 <- as.numeric(n2)
  p <- as.numeric(p)
  m <- as.numeric(m)
  directed <- as.logical(directed)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_bipartite_game,
    type,
    n1,
    n2,
    p,
    m,
    directed,
    mode
  )
  if (igraph_opt("add.vertex.names") && is_named(res$graph)) {
    names(res$types) <- vertex_attr(res$graph, "name", V(res$graph))
  }
  res
}

create_bipartite_impl <- function(
  types,
  edges,
  directed = FALSE
) {
  # Argument checks
  types <- handle_vertex_type_arg(types, res$graph)
  edges <- as.numeric(edges)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_create_bipartite,
    types,
    edges,
    directed
  )

  res
}

full_bipartite_impl <- function(
  n1,
  n2,
  directed = FALSE,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  n1 <- as.numeric(n1)
  n2 <- as.numeric(n2)
  directed <- as.logical(directed)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_full_bipartite,
    n1,
    n2,
    directed,
    mode
  )
  if (igraph_opt("add.vertex.names") && is_named(res$graph)) {
    names(res$types) <- vertex_attr(res$graph, "name")
  }
  res
}

# ==== other-operations-on-bipartite-graphs ====

is_bipartite_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_bipartite,
    graph
  )
  if (igraph_opt("add.vertex.names") && is_named(graph)) {
    names(res$type) <- vertex_attr(graph, "name", V(graph))
  }
  res
}

# ==== project-two-mode-graphs ====

bipartite_projection_impl <- function(
  graph,
  types,
  probe1 = -1
) {
  # Argument checks
  ensure_igraph(graph)
  types <- handle_vertex_type_arg(types, graph)
  probe1 <- as.numeric(probe1)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_bipartite_projection,
    graph,
    types,
    probe1
  )

  res
}

bipartite_projection_size_impl <- function(
  graph,
  types = NULL
) {
  # Argument checks
  ensure_igraph(graph)
  types <- handle_vertex_type_arg(types, graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_bipartite_projection_size,
    graph,
    types
  )

  res
}
