# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== detect ====

is_bipartite_coloring_impl <- function(
  graph,
  types
) {
  # Argument checks
  ensure_igraph(graph)
  types <- handle_vertex_type_arg(types, graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_bipartite_coloring,
    graph,
    types
  )

  res
}

is_edge_coloring_impl <- function(
  graph,
  types
) {
  # Argument checks
  ensure_igraph(graph)
  if (is_missing(types)) {
    if ("color" %in% edge_attr_names(graph)) {
      types <- E(graph)$color
    } else {
      types <- NULL
    }
  }
  if (!is.null(types)) {
    types <- as.numeric(types) - 1
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_edge_coloring,
    graph,
    types
  )

  res
}

is_perfect_impl <- function(
  graph
) {
  # Argument checks
  ensure_igraph(graph)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_perfect,
    graph
  )

  res
}

is_vertex_coloring_impl <- function(
  graph,
  types
) {
  # Argument checks
  ensure_igraph(graph)
  if (is_missing(types)) {
    if ("color" %in% vertex_attr_names(graph)) {
      types <- V(graph)$color
    } else {
      types <- NULL
    }
  }
  if (!is.null(types)) {
    types <- as.numeric(types) - 1
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_is_vertex_coloring,
    graph,
    types
  )

  res
}

# ==== compute ====

vertex_coloring_greedy_impl <- function(
  graph,
  heuristic = c("colored_neighbors", "dsatur")
) {
  # Argument checks
  ensure_igraph(graph)
  heuristic <- switch_igraph_arg(heuristic, "colored_neighbors" = 0L, "dsatur" = 1L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_vertex_coloring_greedy,
    graph,
    heuristic
  )
  res <- res + 1
  if (igraph_opt("add.vertex.names") && is_named(graph)) {
    names(res) <- vertex_attr(graph, "name")
  }
  res
}
