# Generated by tools/split-aaa-auto.R from aaa-auto.R — do not edit by hand
# styler: off

# ==== adjacency-generators ====

adjacency_impl <- function(
  adjmatrix,
  mode = c("directed", "undirected", "upper", "lower", "min", "plus", "max"),
  loops = c("once", "none", "twice")
) {
  # Argument checks
  adjmatrix[] <- as.numeric(adjmatrix)
  mode <- switch_igraph_arg(
    mode,
    "directed" = 0L,
    "undirected" = 1L,
    "upper" = 2L,
    "lower" = 3L,
    "min" = 4L,
    "plus" = 5L,
    "max" = 6L
  )
  loops <- switch_igraph_arg(loops, "none" = 0L, "twice" = 1L, "once" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_adjacency,
    adjmatrix,
    mode,
    loops
  )

  res
}

adjlist_impl <- function(
  adjlist,
  mode = c("out", "in", "all", "total"),
  duplicate = TRUE
) {
  # Argument checks
  adjlist <- lapply(adjlist, function(x) as.numeric(x) - 1)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )
  duplicate <- as.logical(duplicate)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_adjlist,
    adjlist,
    mode,
    duplicate
  )

  res
}

sparse_adjacency_impl <- function(
  adjmatrix,
  mode = c("directed", "undirected", "upper", "lower", "min", "plus", "max"),
  loops = c("once", "none", "twice")
) {
  # Argument checks
  requireNamespace("Matrix", quietly = TRUE)
  adjmatrix <- as(as(as(adjmatrix, "dMatrix"), "generalMatrix"), "CsparseMatrix")
  mode <- switch_igraph_arg(
    mode,
    "directed" = 0L,
    "undirected" = 1L,
    "upper" = 2L,
    "lower" = 3L,
    "min" = 4L,
    "plus" = 5L,
    "max" = 6L
  )
  loops <- switch_igraph_arg(loops, "none" = 0L, "twice" = 1L, "once" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_sparse_adjacency,
    adjmatrix,
    mode,
    loops
  )

  res
}

sparse_weighted_adjacency_impl <- function(
  adjmatrix,
  mode = c("directed", "undirected", "upper", "lower", "min", "plus", "max"),
  loops = c("once", "none", "twice")
) {
  # Argument checks
  requireNamespace("Matrix", quietly = TRUE)
  adjmatrix <- as(as(as(adjmatrix, "dMatrix"), "generalMatrix"), "CsparseMatrix")
  mode <- switch_igraph_arg(
    mode,
    "directed" = 0L,
    "undirected" = 1L,
    "upper" = 2L,
    "lower" = 3L,
    "min" = 4L,
    "plus" = 5L,
    "max" = 6L
  )
  loops <- switch_igraph_arg(loops, "none" = 0L, "twice" = 1L, "once" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_sparse_weighted_adjacency,
    adjmatrix,
    mode,
    loops
  )

  res
}

weighted_adjacency_impl <- function(
  adjmatrix,
  mode = c("directed", "undirected", "upper", "lower", "min", "plus", "max"),
  loops = c("once", "none", "twice")
) {
  # Argument checks
  adjmatrix[] <- as.numeric(adjmatrix)
  mode <- switch_igraph_arg(
    mode,
    "directed" = 0L,
    "undirected" = 1L,
    "upper" = 2L,
    "lower" = 3L,
    "min" = 4L,
    "plus" = 5L,
    "max" = 6L
  )
  loops <- switch_igraph_arg(loops, "none" = 0L, "twice" = 1L, "once" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_weighted_adjacency,
    adjmatrix,
    mode,
    loops
  )

  res
}

weighted_sparsemat_impl <- function(
  A,
  directed,
  attr,
  loops = FALSE
) {
  # Argument checks
  requireNamespace("Matrix", quietly = TRUE)
  A <- as(as(as(A, "dMatrix"), "generalMatrix"), "CsparseMatrix")
  directed <- as.logical(directed)
  loops <- as.logical(loops)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_weighted_sparsemat,
    A,
    directed,
    attr,
    loops
  )

  res
}

# ==== basic-generators ====

create_impl <- function(
  edges,
  n = 0,
  directed = TRUE
) {
  # Argument checks
  edges <- as.numeric(edges)
  n <- as.numeric(n)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_create,
    edges,
    n,
    directed
  )

  res
}

# ==== complete-graph-generators ====

full_citation_impl <- function(
  n,
  directed = TRUE
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_full_citation,
    n,
    directed
  )

  res
}

full_impl <- function(
  n,
  directed = FALSE,
  loops = FALSE
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)
  loops <- as.logical(loops)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_full,
    n,
    directed,
    loops
  )

  res
}

full_multipartite_impl <- function(
  n,
  directed = FALSE,
  mode = c("all", "out", "in", "total")
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)
  mode <- switch_igraph_arg(
    mode,
    "out" = 1L,
    "in" = 2L,
    "all" = 3L,
    "total" = 3L
  )

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_full_multipartite,
    n,
    directed,
    mode
  )

  if (igraph_opt("add.params")) {
    res$name <- 'Full multipartite graph'
    res$n <- n
    res$mode <- mode
  }

  res
}

turan_impl <- function(
  n,
  r
) {
  # Argument checks
  n <- as.numeric(n)
  r <- as.numeric(r)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_turan,
    n,
    r
  )

  if (igraph_opt("add.params")) {
    res$name <- 'Turan graph'
    res$n <- n
    res$r <- r
  }

  res
}

# ==== degree-graph-generators ====

realize_bipartite_degree_sequence_impl <- function(
  degrees1,
  degrees2,
  allowed_edge_types = c("simple", "loops", "multi", "all"),
  method = c("smallest", "largest", "index")
) {
  # Argument checks
  degrees1 <- as.numeric(degrees1)
  degrees2 <- as.numeric(degrees2)
  allowed_edge_types <- switch_igraph_arg(
    allowed_edge_types,
    "simple" = 0L,
    "loop" = 1L,
    "loops" = 1L,
    "multi" = 6L,
    "multiple" = 6L,
    "all" = 7L
  )
  method <- switch_igraph_arg(method, "smallest" = 0L, "largest" = 1L, "index" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_realize_bipartite_degree_sequence,
    degrees1,
    degrees2,
    allowed_edge_types,
    method
  )

  if (igraph_opt("add.params")) {
    res$name <- 'Bipartite graph from degree sequence'
    res$degrees1 <- degrees1
    res$degrees2 <- degrees2
    res$allowed_edge_types <- allowed_edge_types
    res$method <- method
  }

  res
}

realize_degree_sequence_impl <- function(
  out_deg,
  in_deg = NULL,
  allowed_edge_types = c("simple", "loops", "multi", "all"),
  method = c("smallest", "largest", "index")
) {
  # Argument checks
  out_deg <- as.numeric(out_deg)
  if (!is.null(in_deg)) {
    in_deg <- as.numeric(in_deg)
  }
  allowed_edge_types <- switch_igraph_arg(
    allowed_edge_types,
    "simple" = 0L,
    "loop" = 1L,
    "loops" = 1L,
    "multi" = 6L,
    "multiple" = 6L,
    "all" = 7L
  )
  method <- switch_igraph_arg(method, "smallest" = 0L, "largest" = 1L, "index" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_realize_degree_sequence,
    out_deg,
    in_deg,
    allowed_edge_types,
    method
  )

  if (igraph_opt("add.params")) {
    res$name <- 'Graph from degree sequence'
    res$out_deg <- out_deg
    res$in_deg <- in_deg
    res$allowed_edge_types <- allowed_edge_types
    res$method <- method
  }

  res
}

# ==== other-generators ====

de_bruijn_impl <- function(
  m,
  n
) {
  # Argument checks
  m <- as.numeric(m)
  n <- as.numeric(n)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_de_bruijn,
    m,
    n
  )

  res
}

generalized_petersen_impl <- function(
  n,
  k
) {
  # Argument checks
  n <- as.numeric(n)
  k <- as.numeric(k)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_generalized_petersen,
    n,
    k
  )

  res
}

kautz_impl <- function(
  m,
  n
) {
  # Argument checks
  m <- as.numeric(m)
  n <- as.numeric(n)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_kautz,
    m,
    n
  )

  res
}

mycielski_graph_impl <- function(
  k
) {
  # Argument checks
  k <- as.numeric(k)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_mycielski_graph,
    k
  )

  res
}

# ==== pre-defined-generators ====

atlas_impl <- function(
  number = 0
) {
  # Argument checks
  number <- as.numeric(number)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_atlas,
    number
  )

  res
}

famous_impl <- function(
  name
) {
  # Argument checks


  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_famous,
    name
  )

  res
}

# ==== regular-structure-generators ====

circulant_impl <- function(
  n,
  shifts,
  directed = FALSE
) {
  # Argument checks
  n <- as.numeric(n)
  shifts <- as.numeric(shifts)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_circulant,
    n,
    shifts,
    directed
  )

  if (igraph_opt("add.params")) {
    res$name <- 'Circulant graph'
    res$shifts <- shifts
  }

  res
}

cycle_graph_impl <- function(
  n,
  directed = FALSE,
  mutual = FALSE
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)
  mutual <- as.logical(mutual)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_cycle_graph,
    n,
    directed,
    mutual
  )

  res
}

extended_chordal_ring_impl <- function(
  nodes,
  W,
  directed = FALSE
) {
  # Argument checks
  nodes <- as.numeric(nodes)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_extended_chordal_ring,
    nodes,
    W,
    directed
  )

  res
}

hypercube_impl <- function(
  n,
  directed = FALSE
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_hypercube,
    n,
    directed
  )

  res
}

lcf_vector_impl <- function(
  n,
  shifts,
  repeats = 1
) {
  # Argument checks
  n <- as.numeric(n)
  shifts <- as.numeric(shifts)
  repeats <- as.numeric(repeats)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_lcf_vector,
    n,
    shifts,
    repeats
  )

  if (igraph_opt("add.params")) {
    res$name <- 'LCF graph'
  }

  res
}

path_graph_impl <- function(
  n,
  directed = FALSE,
  mutual = FALSE
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)
  mutual <- as.logical(mutual)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_path_graph,
    n,
    directed,
    mutual
  )

  res
}

ring_impl <- function(
  n,
  directed = FALSE,
  mutual = FALSE,
  circular = TRUE
) {
  # Argument checks
  n <- as.numeric(n)
  directed <- as.logical(directed)
  mutual <- as.logical(mutual)
  circular <- as.logical(circular)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_ring,
    n,
    directed,
    mutual,
    circular
  )

  res
}

square_lattice_impl <- function(
  dimvector,
  nei = 1,
  directed = FALSE,
  mutual = FALSE,
  periodic = NULL
) {
  # Argument checks
  dimvector <- as.numeric(dimvector)
  nei <- as.numeric(nei)
  directed <- as.logical(directed)
  mutual <- as.logical(mutual)
  if (!is.null(periodic)) {
    periodic <- as.logical(periodic)
  }

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_square_lattice,
    dimvector,
    nei,
    directed,
    mutual,
    periodic
  )

  res
}

star_impl <- function(
  n,
  mode = c("out", "in", "undirected", "mutual"),
  center = 0
) {
  # Argument checks
  n <- as.numeric(n)
  mode <- switch_igraph_arg(
    mode,
    "out" = 0L,
    "in" = 1L,
    "undirected" = 2L,
    "mutual" = 3L
  )
  center <- as.numeric(center)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_star,
    n,
    mode,
    center
  )

  res
}

triangular_lattice_impl <- function(
  dimvector,
  directed = FALSE,
  mutual = FALSE
) {
  # Argument checks
  dimvector <- as.numeric(dimvector)
  directed <- as.logical(directed)
  mutual <- as.logical(mutual)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_triangular_lattice,
    dimvector,
    directed,
    mutual
  )

  res
}

wheel_impl <- function(
  n,
  mode = c("out", "in", "undirected", "mutual"),
  center = 0
) {
  # Argument checks
  n <- as.numeric(n)
  mode <- switch_igraph_arg(
    mode,
    "out" = 0L,
    "in" = 1L,
    "undirected" = 2L,
    "mutual" = 3L
  )
  center <- as.numeric(center)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_wheel,
    n,
    mode,
    center
  )

  res
}

# ==== tree-generators ====

from_prufer_impl <- function(
  prufer
) {
  # Argument checks
  prufer <- as.numeric(prufer) - 1

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_from_prufer,
    prufer
  )

  if (igraph_opt("add.params")) {
    res$name <- 'Tree from Prufer sequence'
    res$prufer <- prufer
  }

  res
}

kary_tree_impl <- function(
  n,
  children = 2,
  type = c("out", "in", "undirected")
) {
  # Argument checks
  n <- as.numeric(n)
  children <- as.numeric(children)
  type <- switch_igraph_arg(type, "out" = 0L, "in" = 1L, "undirected" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_kary_tree,
    n,
    children,
    type
  )

  res
}

regular_tree_impl <- function(
  h,
  k = 3,
  type = c("undirected", "out", "in")
) {
  # Argument checks
  h <- as.numeric(h)
  k <- as.numeric(k)
  type <- switch_igraph_arg(type, "out" = 0L, "in" = 1L, "undirected" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_regular_tree,
    h,
    k,
    type
  )

  res
}

symmetric_tree_impl <- function(
  branches,
  type = c("out", "in", "undirected")
) {
  # Argument checks
  branches <- as.numeric(branches)
  type <- switch_igraph_arg(type, "out" = 0L, "in" = 1L, "undirected" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_symmetric_tree,
    branches,
    type
  )

  res
}

tree_from_parent_vector_impl <- function(
  parents,
  type = c("out", "in", "undirected")
) {
  # Argument checks
  parents <- as.numeric(parents) - 1
  type <- switch_igraph_arg(type, "out" = 0L, "in" = 1L, "undirected" = 2L)

  on.exit(.Call(R_igraph_finalizer))
  # Function call
  res <- .Call(
    R_igraph_tree_from_parent_vector,
    parents,
    type
  )

  res
}
