name: Assign AI Issue to Copilot

on:
  # Run hourly
  schedule:
    - cron: "0 * * * *"
  # Allow manual trigger
  workflow_dispatch:
  # Run when workflow changes
  push:
    paths:
      - .github/workflows/assign-ai-issue.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}
  cancel-in-progress: true

jobs:
  check_fork:
    runs-on: ubuntu-24.04
    outputs:
      is_forked: ${{ steps.check.outputs.is_forked }}
    steps:
      - name: Check if the repo is forked
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          is_forked=$(gh api repos/${{ github.repository }} | jq .fork)
          echo "is_forked=${is_forked}" >> $GITHUB_OUTPUT
        shell: bash

  assign_issue:
    runs-on: ubuntu-24.04
    needs: check_fork
    if: needs.check_fork.outputs.is_forked == 'false'
    permissions:
      issues: write
    steps:
      - name: Find and assign oldest unassigned AI issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail

          # Get all open, unassigned issues with the "AI 🤖" label, sorted by creation date (oldest first)
          oldest_issue=$(gh issue list \
            --repo "$REPO" \
            --label "AI 🤖" \
            --state open \
            --json number,createdAt,assignees \
            --jq 'map(select(.assignees | length == 0)) | sort_by(.createdAt) | .[0].number')

          if [ -n "$oldest_issue" ] && [ "$oldest_issue" != "null" ]; then
            echo "Found unassigned AI issue #$oldest_issue"
            echo "Assigning to @copilot"

            # Assign the issue to Copilot using the API
            # https://github.com/cli/cli/issues/11809
            response=$(curl -L \
              --fail-with-body \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$REPO/issues/$oldest_issue/assignees" \
              -d '{"assignees":["copilot"]}')

            # Verify that copilot is in the assignees list
            if echo "$response" | jq -e '.assignees[] | select(.login == "copilot")' > /dev/null; then
              echo "✓ Successfully assigned to copilot"
            else
              echo "✗ Failed to assign to copilot"
              echo "Response: $response"
              exit 1
            fi

            # Add a comment to the issue
            gh issue comment "$oldest_issue" --repo "$REPO" --body "🤖 This issue has been assigned to Copilot for automated handling."

            echo "Successfully assigned issue #$oldest_issue"
          else
            echo "No unassigned AI issues found"
          fi
        shell: bash
