name: Claude Assistant
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: anthropics/claude-code-action@beta
        id: claude
        with:
          allowed_tools: |
            Bash
            R
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: add custom trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          # Optional: add assignee trigger for issues
          # assignee_trigger: "claude"
          # Optional: add custom environment variables (YAML format)
          # claude_env: |
          #   NODE_ENV: test
          #   DEBUG: true
          #   API_URL: https://api.example.com
          # Optional: limit the number of conversation turns
          max_turns: "20"

      - name: Post failure comment
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let commentBody = `### Claude Assistant Failure 🚨

            I encountered an error while processing your request. This could be due to:

            - **API Rate Limits**: Too many requests in a short period
            - **Timeout**: The task took longer than expected to complete
            - **Resource Constraints**: The task required more resources than available
            - **Configuration Issues**: There may be an issue with the Claude configuration
            - **External Dependencies**: Required services or APIs may be unavailable

            **What you can try:**
            - Wait a few minutes and try again with the same trigger phrase
            - Break down complex requests into smaller, more specific tasks
            - Check if there are any ongoing issues with GitHub Actions or the Anthropic API

            **Job Details:**
            - Workflow Run: [${context.runId}](${context.payload.repository.html_url}/actions/runs/${context.runId})
            - Triggered by: @${context.actor}
            - Failure occurred at: ${new Date().toISOString()}

            If this issue persists, please report it at https://github.com/anthropics/claude-code-action/issues`;

            if (context.eventName === 'issue_comment' || context.eventName === 'issues') {
              // Post comment on issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            } else if (context.eventName === 'pull_request' || context.eventName === 'pull_request_review' || context.eventName === 'pull_request_review_comment') {
              // Post comment on PR
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: commentBody
              });
            }
