# Helper workflow to trigger rcc for each commit on a branch

on:
  push:
    branches:
      - each-*

name: rcc

jobs:
  rcc-smoke:
    runs-on: ubuntu-24.04
    outputs:
      sha: ${{ steps.commit.outputs.sha }}
      versions-matrix: ${{ steps.versions-matrix.outputs.matrix }}
      dep-suggests-matrix: ${{ steps.dep-suggests-matrix.outputs.matrix }}

    name: "Trigger rcc workflow for each commit"

    # Begin custom: services
    # End custom: services

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Enumerate all commits from the repository's main branch
        run: |
          git remote -v
          git fetch --all
          # Get name of main branch of repository
          # origin/HEAD isn't known here
          main=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
          commits=$(git log --pretty=format:"%H" origin/${main}.. --)
          echo $commits
        shell: bash
